import fs from "node:fs";
import vm from "node:vm";
import { compileFileResult } from "./src/main/js/compiler.ts";
import * as runtime from "./src/main/js/runtime.ts";
const out = "./tests/out/selfhost/parity/selfhost.debug.js";
const r = compileFileResult("./src/main/tuff/selfhost.tuff", out, { enableModules: true, modules: { moduleBaseDir: "./src/main/tuff" }, resolve: { hostBuiltins: Object.keys(runtime), allowHostPrefix: "" } });
if (!r.ok) throw r.error;
const js = fs.readFileSync(out, "utf8");
const s = { module: { exports: {} }, exports: {}, console, ...runtime };
vm.runInNewContext(js, s);
const src = "fn takes_i32(x: I32) : I32 => x;\nfn main() : I32 => takes_i32(true);\n";
s.lex_init(src); s.lex_all(); s.parse_init();
const p = s.p_parse_program();
const body = s.node_get_data1(p);
const f = s.vec_get(body, 0);
const typeNode = s.vec_get(s.vec_get(s.node_get_data3(f), 0), 1);
console.log('typeNode', typeNode, typeof typeNode);
console.log('node_kind direct', s.node_kind(typeNode));
console.log('node_kind via eval', vm.runInNewContext('node_kind(' + typeNode + ')', s));
console.log('cmp eval', vm.runInNewContext('(function(){ let k=node_kind(' + typeNode + '); return k==40; })()', s));
console.log('fnResult', s.type_name_from_type_node(typeNode));
