import { describe, expect, it } from "vitest";
import ts from "typescript";
import { compileTuffToTS } from "../src/compileTuffToTS";

function runPipeline(tuffSource: string, stdIn: number[] = []): unknown {
  const tsCode = compileTuffToTS(tuffSource);
  const jsCode = ts.transpileModule(tsCode, {
    compilerOptions: {
      target: ts.ScriptTarget.ES2022,
      module: ts.ModuleKind.None,
    },
  }).outputText;

  return new Function("__tuff_stdin", `${jsCode}\nreturn __tuff_result;`)(
    stdIn,
  );
}

describe("compileTuffToTS", () => {
  it("returns stubbed TypeScript output", () => {
    const input = "let x = 1";
    const output = compileTuffToTS(input);

    expect(output).toContain("Generated by compileTuffToTS (stub)");
    expect(output).toContain(
      "TODO: Replace with real Tuff -> TypeScript compilation logic.",
    );
    expect(output).toContain("Input size: 9 characters");
    expect(output).toContain("export {};");
  });

  it("handles empty input", () => {
    const output = compileTuffToTS("");
    expect(output).toContain("const __tuff_result: number = 0;");
  });

  it("pipeline compiles and executes empty input to 0", () => {
    expect(runPipeline("")).toBe(0);
  });

  it("pipeline compiles and executes 100U8 to 100", () => {
    expect(runPipeline("100U8")).toBe(100);
  });

  it("fails compilation for out-of-range literals", () => {
    expect(() => compileTuffToTS("256U8")).toThrow(/out of range/i);
  });

  it("fails compilation for invalid literal syntax", () => {
    expect(() => compileTuffToTS("abcU8")).toThrow(/invalid/i);
    expect(() => compileTuffToTS("-1U8")).toThrow(/invalid/i);
  });

  it("pipeline supports read<T>() for integer families", () => {
    const cases: Array<{
      source: string;
      stdIn: number[];
      expected: number | bigint;
    }> = [
      { source: "read<U8>()", stdIn: [100], expected: 100 },
      { source: "read<U16>()", stdIn: [0x34, 0x12], expected: 0x1234 },
      {
        source: "read<U32>()",
        stdIn: [0x78, 0x56, 0x34, 0x12],
        expected: 0x12345678,
      },
      {
        source: "read<U64>()",
        stdIn: [0x08, 0x07, 0x06, 0x05, 0x04, 0x03, 0x02, 0x01],
        expected: 0x0102030405060708n,
      },
      { source: "read<I8>()", stdIn: [0xff], expected: -1 },
      { source: "read<I16>()", stdIn: [0x00, 0x80], expected: -32768 },
      { source: "read<I32>()", stdIn: [0xff, 0xff, 0xff, 0xff], expected: -1 },
      {
        source: "read<I64>()",
        stdIn: [0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff],
        expected: -1n,
      },
    ];

    for (const { source, stdIn, expected } of cases) {
      expect(runPipeline(source, stdIn)).toBe(expected);
    }
  });

  it("simple variable binding: let x : U8 = 100U8; x", () => {
    expect(runPipeline("let x : U8 = 100U8; x")).toBe(100);
  });

  it("assignable upcast: let x : U8 = 10U8; let y : U16 = x; y", () => {
    expect(runPipeline("let x : U8 = 10U8; let y : U16 = x; y")).toBe(10);
  });

  it("chained bindings with read", () => {
    expect(
      runPipeline("let x : U8 = 5U8; let y : U16 = read<U16>(); y", [
        0x34, 0x12,
      ]),
    ).toBe(0x1234);
  });

  it("fails on out-of-scope variable reference", () => {
    expect(() => compileTuffToTS("let x : U8 = 100U8; y")).toThrow(
      /undefined|not found|out.?of.?scope/i,
    );
  });

  it("fails on invalid type assignability (unsigned to signed)", () => {
    expect(() => compileTuffToTS("let x : U8 = 100U8; let y : I8 = x; y")).toThrow(
      /assignable|incompatible/i,
    );
  });

  it("allows variable shadowing", () => {
    expect(runPipeline("let x : U8 = 10U8; let x : U8 = 20U8; x")).toBe(20);
  });
});
