import { describe, expect, it } from "vitest";
import { compileTuffToTS } from "../src/compileTuffToTS";

describe("compileTuffToTS", () => {
  it("returns stubbed TypeScript output", () => {
    const input = "let x = 1";
    const output = compileTuffToTS(input);

    expect(output).toContain("Generated by compileTuffToTS (stub)");
    expect(output).toContain(
      "TODO: Replace with real Tuff -> TypeScript compilation logic.",
    );
    expect(output).toContain("Input size: 9 characters");
    expect(output).toContain("export {};");
  });

  it("handles empty input", () => {
    const output = compileTuffToTS("");
    expect(output).toContain("Input size: 0 characters");
  });
});
