// Generated by scripts/refactor/split-compile.ts

import type { Result } from "../../types";

// Token interfaces
export interface NumberToken {
  type: "NUMBER";
  value: string;
}

export interface OperatorToken {
  type: "OPERATOR";
  value: "+" | "-" | "*" | "/" | "%";
}

export interface BoolToken {
  type: "BOOL";
  value: "true" | "false";
}

export interface CharToken {
  type: "CHAR";
  value: string;
}

export interface StringToken {
  type: "STRING";
  value: number[];
}

export interface ComparisonToken {
  type: "COMPARISON";
  value: "<" | ">" | "<=" | ">=" | "==" | "!=";
}

export interface LogicalToken {
  type: "LOGICAL";
  value: "&&" | "||" | "!";
}

export interface IdentifierToken {
  type: "IDENTIFIER";
  value: string;
}

export interface KeywordToken {
  type: "KEYWORD";
  value:
    | "let"
    | "extern"
    | "object"
    | "type"
    | "then"
    | "this"
    | "is"
    | "mut"
    | "if"
    | "else"
    | "while"
    | "break"
    | "continue"
    | "match"
    | "case"
    | "fn"
    | "return"
    | "struct";
}

export interface LParenToken {
  type: "LPAREN";
}

export interface RParenToken {
  type: "RPAREN";
}

export interface LTToken {
  type: "LT";
}

export interface GTToken {
  type: "GT";
}

export interface ColonToken {
  type: "COLON";
}

export interface DoubleColonToken {
  type: "DOUBLE_COLON";
}

export interface SemicolonToken {
  type: "SEMICOLON";
}

export interface ArrowToken {
  type: "ARROW";
}

export interface AssignToken {
  type: "ASSIGN";
}

export interface PlusAssignToken {
  type: "PLUS_ASSIGN";
}

export interface MinusAssignToken {
  type: "MINUS_ASSIGN";
}

export interface MultAssignToken {
  type: "MULT_ASSIGN";
}

export interface DivAssignToken {
  type: "DIV_ASSIGN";
}

export interface ModAssignToken {
  type: "MOD_ASSIGN";
}

export interface LBraceToken {
  type: "LBRACE";
}

export interface RBraceToken {
  type: "RBRACE";
}

export interface CommaToken {
  type: "COMMA";
}

export interface PipeToken {
  type: "PIPE";
}

export interface DotToken {
  type: "DOT";
}

export interface AddressOfToken {
  type: "ADDRESS_OF";
}

export interface LBracketToken {
  type: "LBRACKET";
}

export interface RBracketToken {
  type: "RBRACKET";
}

export interface EOFToken {
  type: "EOF";
}

export type Token =
  | NumberToken
  | OperatorToken
  | IdentifierToken
  | KeywordToken
  | BoolToken
  | CharToken
  | StringToken
  | ComparisonToken
  | LogicalToken
  | LParenToken
  | RParenToken
  | LBraceToken
  | RBraceToken
  | LBracketToken
  | RBracketToken
  | LTToken
  | GTToken
  | ColonToken
  | DoubleColonToken
  | SemicolonToken
  | ArrowToken
  | AssignToken
  | PlusAssignToken
  | MinusAssignToken
  | MultAssignToken
  | DivAssignToken
  | ModAssignToken
  | CommaToken
  | PipeToken
  | DotToken
  | AddressOfToken
  | EOFToken;

// AST node interfaces
export interface NumberNode {
  kind: "number";
  value: string;
}

export interface ReadNode {
  kind: "read";
  type: string;
}

export interface VariableNode {
  kind: "variable";
  name: string;
}

export interface MoveNode {
  kind: "move";
  name: string;
  type: string;
}

export interface ModuleReferenceNode {
  kind: "module-reference";
  moduleName: string;
  runtimeName: string;
  type: string;
}

export interface ThisNode {
  kind: "this";
  scope: ScopeFrame;
}

export interface BinaryNode {
  kind: "binary";
  left: ASTNode;
  operator: "+" | "-" | "*" | "/" | "%";
  right: ASTNode;
}

export interface ComparisonNode {
  kind: "comparison";
  left: ASTNode;
  operator: "<" | ">" | "<=" | ">=" | "==" | "!=";
  right: ASTNode;
}

export interface IsNode {
  kind: "is";
  expression: ASTNode;
  checkedType: string;
  matches: boolean;
  runtimeCheck: boolean;
}

export interface UnionWrapNode {
  kind: "union-wrap";
  expression: ASTNode;
  unionType: string;
  armType: string;
}

export interface LogicalNode {
  kind: "logical";
  operator: "&&" | "||";
  left: ASTNode;
  right: ASTNode;
}

export interface UnaryLogicalNode {
  kind: "unary-logical";
  operator: "!";
  operand: ASTNode;
}

export interface UnaryOpNode {
  kind: "unary-op";
  operator: "*" | "&" | "&mut";
  operand: ASTNode;
}

export interface BooleanNode {
  kind: "boolean";
  value: boolean;
}

export interface CharNode {
  kind: "char";
  value: string;
}

export interface StringNode {
  kind: "string";
  value: number[];
}

export interface LetNode {
  kind: "let";
  mutable: boolean;
  name: string;
  type: string;
  aliasType?: string;
  destructorFunction?: string;
  initializer: ASTNode;
}

export interface DestructureNode {
  kind: "destructure";
  statements: LetNode[];
}

export interface AssignNode {
  kind: "assign";
  name: string;
  value: ASTNode;
}

export interface FieldAssignNode {
  kind: "field-assign";
  object: ASTNode;
  fieldName: string;
  value: ASTNode;
}

export interface DerefAssignNode {
  kind: "deref-assign";
  target: ASTNode;
  value: ASTNode;
  targetVar?: string; // The name of the variable being assigned (for pointers)
}

export interface BlockNode {
  kind: "block";
  statements: ASTNode[];
  result: ASTNode;
}

export interface IfNode {
  kind: "if";
  condition: ASTNode;
  thenBranch: ASTNode;
  elseBranch: ASTNode | undefined;
}

export interface WhileNode {
  kind: "while";
  condition: ASTNode;
  body: ASTNode;
}

export interface BreakNode {
  kind: "break";
}

export interface ContinueNode {
  kind: "continue";
}

export interface ReturnNode {
  kind: "return";
  value: ASTNode;
}

export interface CasePattern {
  type: "literal" | "boolean" | "wildcard";
  value?: string | boolean; // value for literals/booleans, undefined for wildcard
}

export interface MatchCase {
  pattern: CasePattern;
  result: ASTNode;
}

export interface MatchNode {
  kind: "match";
  matchExpr: ASTNode;
  cases: MatchCase[];
}

export interface FunctionParameter {
  name: string;
  type: string;
  aliasType?: string;
  destructorFunction?: string;
}

export interface FunctionNode {
  kind: "function";
  name: string;
  typeParameters: string[];
  parameters: FunctionParameter[];
  returnType: string;
  body: ASTNode;
  isDestructor?: boolean;
}

export interface ObjectNode {
  kind: "object";
  name: string;
  type: string;
  body: ASTNode[];
  scope: ScopeFrame;
}

export interface ModuleNode {
  kind: "module";
  moduleName: string;
  runtimeName: string;
  type: string;
  body: ASTNode;
  scope: ScopeFrame;
  implementationOrigin?: ModuleImplementationOrigin;
  externalProviderVar?: string;
  externBindings?: ExternBindingInfo[];
}

export interface ClosureNode {
  kind: "closure";
  parameters: FunctionParameter[];
  returnType: string;
  body: ASTNode;
}

export interface FunctionCallNode {
  kind: "function-call";
  name: string;
  arguments: ASTNode[];
  typeArguments?: string[];
  parameterTypes?: string[];
  returnType?: string;
}

export interface CallNode {
  kind: "call";
  callee: ASTNode;
  arguments: ASTNode[];
  returnType?: string;
}

export interface StructField {
  name: string;
  type: string;
  mutable: boolean;
  aliasType?: string;
  destructorFunction?: string;
}

export interface StructNode {
  kind: "struct";
  name: string;
  typeParameters: string[];
  fields: StructField[];
}

export interface TypeAliasNode {
  kind: "type-alias";
  name: string;
  targetType: string;
  destructorName?: string;
}

export interface ExternModuleNode {
  kind: "extern-module";
  moduleName: string;
}

export interface ExternFunctionNode {
  kind: "extern-function";
  name: string;
  parameters: FunctionParameter[];
  returnType: string;
}

export interface ExternLetNode {
  kind: "extern-let";
  name: string;
  type: string;
}

export interface ExternTypeNode {
  kind: "extern-type";
  name: string;
  targetType: string;
}

export interface StructInstantiationField {
  name: string;
  value: ASTNode;
}

export interface StructInstantiationNode {
  kind: "struct-instantiation";
  structName: string;
  fields: StructInstantiationField[];
  typeArguments?: string[];
}

export interface FieldAccessNode {
  kind: "field-access";
  object: ASTNode;
  fieldName: string;
  typeArguments?: string[];
}

export interface ArrayLiteralNode {
  kind: "array-literal";
  elements: ASTNode[];
  generator?: ASTNode;
  repeatCount?: number;
  elemType?: string;
}

export interface ArrayAccessNode {
  kind: "array-access";
  array: ASTNode;
  index: ASTNode;
}

export interface ArraySliceNode {
  kind: "array-slice";
  array: ASTNode;
  start: number;
  end: number;
}

export interface ArrayAssignNode {
  kind: "array-assign";
  array: ASTNode;
  index: ASTNode;
  value: ASTNode;
}

export type ASTNode =
  | NumberNode
  | ReadNode
  | ModuleReferenceNode
  | VariableNode
  | MoveNode
  | ThisNode
  | BinaryNode
  | ComparisonNode
  | IsNode
  | UnionWrapNode
  | LogicalNode
  | UnaryLogicalNode
  | UnaryOpNode
  | BooleanNode
  | CharNode
  | StringNode
  | LetNode
  | DestructureNode
  | AssignNode
  | FieldAssignNode
  | DerefAssignNode
  | BlockNode
  | IfNode
  | WhileNode
  | BreakNode
  | ContinueNode
  | ReturnNode
  | MatchNode
  | FunctionNode
  | ObjectNode
  | ModuleNode
  | ClosureNode
  | FunctionCallNode
  | CallNode
  | TypeAliasNode
  | ExternModuleNode
  | ExternFunctionNode
  | ExternLetNode
  | ExternTypeNode
  | StructNode
  | StructInstantiationNode
  | FieldAccessNode
  | ArrayLiteralNode
  | ArrayAccessNode
  | ArraySliceNode
  | ArrayAssignNode;

// Refinement type interfaces
export interface RefinementConstraint {
  operator: "<" | ">" | "<=" | ">=" | "==" | "!=";
  value: string; // The constraint value (as string literal, for backward compat)
  valueExpr?: ASTNode; // The constraint value as an expression (for variables/arithmetic)
  baseType?: string; // For multi-constraint like "I32 > 0 && I32 < 100", track base type
  isOr?: boolean; // True if this constraint is OR'd with the previous one
}

export interface RefinementType {
  baseType: string;
  constraints: RefinementConstraint[];
}

// Variable info interface
export interface VariableInfo {
  type: string;
  mutable: boolean;
  aliasType?: string;
  destructorFunction?: string;
  moved?: boolean;
  refinement?: RefinementType; // Optional refinement constraints
  initValue?: string; // The literal value (for constants), if available
  pointsTo?: string; // For pointers: the name of the variable it points to
  sliceLength?: number; // For slices: known compile-time length
}

export interface ScopeBinding {
  kind: "variable" | "function";
  type: string;
  mutable: boolean;
  assignable: boolean;
  typeParameters?: string[];
}

export interface ScopeFrame {
  kind: "normal" | "object";
  members: Map<string, ScopeBinding>;
  parent: ScopeFrame | undefined;
}

export interface ObjectInfo {
  name: string;
  type: string;
  scope: ScopeFrame;
}

export interface TypeNarrowingInfo {
  trueBranch: Map<string, string>;
  falseBranch: Map<string, string>;
}

export interface ParsedTypeAliasDeclaration {
  name: string;
  targetType: string;
  destructorName?: string;
}

export interface ParsedTypeReference {
  type: string;
  aliasType?: string;
  destructorFunction?: string;
}

export interface DestructuredBinding {
  sourceName: string;
  bindingName: string;
}

export interface ProjectCompileInput {
  entryModule: string;
  files: Map<string, string> | Record<string, string>;
  target?: ProjectTarget;
}

export type ProjectTarget = "js";

export type ModuleImplementationOrigin = "tuff" | "external" | "hybrid";

export interface ExternalModuleProviderInfo {
  path: string;
  moduleName: string;
  target: ProjectTarget;
  source: string;
  runtimeName: string;
}

export interface ExternBindingInfo {
  name: string;
  kind: "function" | "value";
}

export interface ModuleCompilationInfo {
  path: string;
  moduleName: string;
  typeName: string;
  runtimeName: string;
  source: string;
  scope: ScopeFrame;
  dependencies: string[];
  target: ProjectTarget;
  implementationOrigin: ModuleImplementationOrigin;
  externalProvider?: ExternalModuleProviderInfo;
  externModuleName?: string;
  externBindings?: ExternBindingInfo[];
  ast?: ASTNode;
}

export interface SuccessfulEvaluation {
  success: true;
  value: number;
}

export interface FailedEvaluation {
  success: false;
}

export type EvaluationResult = SuccessfulEvaluation | FailedEvaluation;

export interface TokenizedCharLiteral {
  token: CharToken;
  nextPos: number;
}

export interface TokenizedStringLiteral {
  token: StringToken;
  nextPos: number;
}

export interface ParsedFunctionType {
  parameterTypes: string[];
  returnType: string;
}

export interface ResolvedThisMemberAccess {
  ownerScope: ScopeFrame;
  memberName: string;
  binding: ScopeBinding;
}

export interface FunctionInfo {
  typeParameters: string[];
  parameters: FunctionParameter[];
  returnType: string;
}

export interface StructInfo {
  typeParameters: string[];
  fields: StructField[];
}

export interface Parser {
  tokens: Token[];
  pos: number;
  variables: Map<string, VariableInfo>;
  functions: Map<string, FunctionInfo>;
  modules: Map<string, ModuleCompilationInfo>;
  aliases: Map<string, string>;
  aliasDeclarations: Map<string, string>;
  aliasDestructors: Map<string, string>;
  structs: Map<string, StructInfo>;
  structNames: Set<string>;
  objects: Map<string, ObjectInfo>;
  genericTypeParameters: string[];
  inLoop: boolean;
  currentFunctionReturnType: string | undefined;
  globalScope: ScopeFrame;
  currentScope: ScopeFrame;
  currentModuleName: string | undefined;
  // Type narrowing: track variables with proven constraints (from control flow guards)
  provenConstraints: Map<string, RefinementType>; // e.g., "x" -> I32 > 100
}

export interface ParsedNumberLiteral {
  numericPart: string;
  typeAnnotation: string;
}

export interface ParsedArrayType {
  elementType: string;
  length: number;
}

export interface ParsedSliceType {
  elementType: string;
}

export interface ParsedSliceReferenceType {
  elementType: string;
  mutable: boolean;
}

export interface ArrayLikeInfo {
  elementType: string;
  length: number | undefined;
  mutable: boolean;
  isSlice: boolean;
}

export interface AssignmentOperatorInfo {
  isCompound: boolean;
  operator: "+" | "-" | "*" | "/" | "%";
}

export interface ParseBinaryConfig {
  // eslint-disable-next-line no-unused-vars
  nextParser: (p: Parser) => Result<ASTNode, string>;
  // eslint-disable-next-line no-unused-vars
  tokenMatcher: (tok: Token) => boolean;
  // eslint-disable-next-line no-unused-vars
  operatorExtractor: (tok: Token) => string;
  nodeMaker: (
    // eslint-disable-next-line no-unused-vars
    operator: string,
    // eslint-disable-next-line no-unused-vars
    left: ASTNode,
    // eslint-disable-next-line no-unused-vars
    right: ASTNode,
  ) => BinaryNode | ComparisonNode | LogicalNode;
}
