// Generated by scripts/refactor/split-compile.ts

import { err, ok } from "../../types";
import type { Result } from "../../types";
import type {
  ExternalModuleProviderInfo,
  ModuleCompilationInfo,
  ProjectCompileInput,
  ProjectTarget,
  Token,
} from "./ast";
import { createObjectTypeName, createScopeFrame } from "./scope";
import { isDigit, isLetter, tokenize } from "./tokenization";

export function normalizeProjectFilePath(path: string): string {
  return path.replaceAll("\\", "/");
}

export function isIdentifierName(text: string): boolean {
  if (text.length === 0) {
    return false;
  }

  const first = text[0];
  if (first !== "_" && !isLetter(first)) {
    return false;
  }

  for (let i = 1; i < text.length; i++) {
    const char = text[i];
    if (char !== "_" && !isLetter(char) && !isDigit(char)) {
      return false;
    }
  }

  return true;
}

export function inferModuleNameFromPath(
  path: string,
  allowedExtensions: string[] = [".tuff"],
): Result<string, string> {
  const normalizedPath = normalizeProjectFilePath(path);
  const matchedExtension = allowedExtensions.find((extension) =>
    normalizedPath.endsWith(extension),
  );
  if (!matchedExtension) {
    return err(
      "Project file path must end with one of " +
        allowedExtensions.map((extension) => "'" + extension + "'").join(", ") +
        ": " +
        path,
    );
  }

  const withoutExtension = normalizedPath.slice(0, -matchedExtension.length);
  const segments = withoutExtension
    .split("/")
    .map((segment) => segment.trim())
    .filter((segment) => segment.length > 0);

  if (segments.length === 0) {
    return err("Project file path must contain a module name: " + path);
  }

  for (const segment of segments) {
    if (!isIdentifierName(segment)) {
      return err(
        "Invalid module path segment '" + segment + "' in path '" + path + "'",
      );
    }
  }

  return ok(segments.join("::"));
}

export function createModuleRuntimeName(moduleName: string): string {
  let runtimeName = "__tuffModule";

  for (const char of moduleName) {
    if (char === ":") {
      runtimeName += "_";
    } else if (char === "_" || isLetter(char) || isDigit(char)) {
      runtimeName += char;
    } else {
      runtimeName += "_";
    }
  }

  return runtimeName;
}

export function createModuleResultName(runtimeName: string): string {
  return runtimeName + "__result";
}

export function createExternalProviderRuntimeName(moduleName: string): string {
  return createModuleRuntimeName(moduleName) + "__external";
}

export function getProjectTarget(input: ProjectCompileInput): ProjectTarget {
  return input.target ?? "js";
}

export function normalizeProjectFiles(
  files: Map<string, string> | Record<string, string>,
): Map<string, string> {
  if (files instanceof Map) {
    return new Map(
      Array.from(files.entries(), ([path, source]) => [
        normalizeProjectFilePath(path),
        source,
      ]),
    );
  }

  return new Map(
    Object.entries(files).map(([path, source]) => [
      normalizeProjectFilePath(path),
      source,
    ]),
  );
}

export function createProjectModuleInfo(
  path: string,
  source: string,
  target: ProjectTarget = "js",
): Result<ModuleCompilationInfo, string> {
  const moduleName = inferModuleNameFromPath(path, [".tuff"]);
  if (!moduleName.ok) {
    return moduleName;
  }

  return ok({
    path,
    moduleName: moduleName.value,
    typeName: createObjectTypeName(moduleName.value),
    runtimeName: createModuleRuntimeName(moduleName.value),
    source,
    scope: createScopeFrame(undefined, "object"),
    dependencies: [],
    target,
    implementationOrigin: "tuff",
  });
}

export function createExternalProviderInfo(
  path: string,
  source: string,
  target: ProjectTarget = "js",
): Result<ExternalModuleProviderInfo, string> {
  const moduleName = inferModuleNameFromPath(path, [".js"]);
  if (!moduleName.ok) {
    return moduleName;
  }

  return ok({
    path,
    moduleName: moduleName.value,
    target,
    source,
    runtimeName: createExternalProviderRuntimeName(moduleName.value),
  });
}

export function tokenizeProjectSource(source: string): Result<Token[], string> {
  if (source !== source.trim()) {
    return err("Leading or trailing whitespace is not allowed");
  }

  return tokenize(source);
}

export function tokenizeProjectModule(
  moduleInfo: ModuleCompilationInfo,
): Result<Token[], string> {
  const tokenResult = tokenizeProjectSource(moduleInfo.source);
  if (!tokenResult.ok) {
    return err(
      "Module '" +
        moduleInfo.moduleName +
        "' could not be tokenized: " +
        tokenResult.error,
    );
  }

  return tokenResult;
}

export function collectModuleReferencesFromTokens(tokens: Token[]): string[] {
  const references: string[] = [];

  for (let i = 0; i < tokens.length; i++) {
    const currentToken = tokens[i];
    const nextToken = tokens[i + 1];
    if (
      currentToken?.type !== "IDENTIFIER" ||
      nextToken?.type !== "DOUBLE_COLON"
    ) {
      continue;
    }

    const segments = [currentToken.value];
    let cursor = i + 1;

    while (tokens[cursor]?.type === "DOUBLE_COLON") {
      const identToken = tokens[cursor + 1];
      if (identToken?.type !== "IDENTIFIER") {
        break;
      }
      segments.push(identToken.value);
      cursor += 2;
    }

    if (segments.length > 1) {
      const moduleName = segments.join("::");
      if (!references.includes(moduleName)) {
        references.push(moduleName);
      }
      i = cursor - 1;
    }
  }

  return references;
}

export function collectDeclaredValueNamesFromTokens(
  tokens: Token[],
): Set<string> {
  const names = new Set<string>();

  for (let i = 0; i < tokens.length; i++) {
    const token = tokens[i];
    if (token?.type !== "KEYWORD") {
      continue;
    }

    if (token.value === "let") {
      let cursor = i + 1;
      const maybeMut = tokens[cursor];
      if (maybeMut?.type === "KEYWORD" && maybeMut.value === "mut") {
        cursor++;
      }

      const declared = tokens[cursor];
      if (declared?.type === "IDENTIFIER") {
        names.add(declared.value);
      }
      continue;
    }

    if (token.value === "extern") {
      const nextToken = tokens[i + 1];

      if (nextToken?.type === "KEYWORD" && nextToken.value === "let") {
        const declared = tokens[i + 2];
        if (declared?.type === "IDENTIFIER") {
          names.add(declared.value);
        }
      } else if (nextToken?.type === "KEYWORD" && nextToken.value === "fn") {
        const declared = tokens[i + 2];
        if (declared?.type === "IDENTIFIER") {
          names.add(declared.value);
        }
      }
      continue;
    }

    if (token.value === "fn" || token.value === "object") {
      const declared = tokens[i + 1];
      if (declared?.type === "IDENTIFIER") {
        names.add(declared.value);
      }
    }
  }

  return names;
}

export function collectProjectModuleReferencesFromTokens(
  tokens: Token[],
  modules: Map<string, ModuleCompilationInfo>,
): string[] {
  const references = collectModuleReferencesFromTokens(tokens);
  const declaredNames = collectDeclaredValueNamesFromTokens(tokens);

  for (let i = 0; i < tokens.length; i++) {
    const token = tokens[i];
    if (token?.type !== "IDENTIFIER") {
      continue;
    }

    if (declaredNames.has(token.value)) {
      continue;
    }

    const moduleInfo = modules.get(token.value);
    if (!moduleInfo || moduleInfo.moduleName.includes("::")) {
      continue;
    }

    const previousToken = i > 0 ? tokens[i - 1] : undefined;
    if (
      previousToken?.type === "DOT" ||
      previousToken?.type === "DOUBLE_COLON"
    ) {
      continue;
    }

    if (!references.includes(moduleInfo.moduleName)) {
      references.push(moduleInfo.moduleName);
    }
  }

  return references;
}

export function buildProjectModuleRegistry(
  files: Map<string, string> | Record<string, string>,
  target: ProjectTarget = "js",
): Result<Map<string, ModuleCompilationInfo>, string> {
  const normalizedFiles = normalizeProjectFiles(files);
  const modules = new Map<string, ModuleCompilationInfo>();
  const externalProviders = new Map<string, ExternalModuleProviderInfo>();

  for (const [path, source] of normalizedFiles) {
    if (path.endsWith(".tuff")) {
      const moduleInfo = createProjectModuleInfo(path, source, target);
      if (!moduleInfo.ok) {
        return moduleInfo;
      }

      if (modules.has(moduleInfo.value.moduleName)) {
        return err(
          "Duplicate inferred module name '" +
            moduleInfo.value.moduleName +
            "' from path '" +
            path +
            "'",
        );
      }

      modules.set(moduleInfo.value.moduleName, moduleInfo.value);
      continue;
    }

    if (path.endsWith(".js")) {
      const providerInfo = createExternalProviderInfo(path, source, target);
      if (!providerInfo.ok) {
        return providerInfo;
      }

      if (externalProviders.has(providerInfo.value.moduleName)) {
        return err(
          "Duplicate external provider for module '" +
            providerInfo.value.moduleName +
            "' from path '" +
            path +
            "'",
        );
      }

      externalProviders.set(providerInfo.value.moduleName, providerInfo.value);
      continue;
    }

    return err(
      "Project file path must end with one of '.tuff', '.js': " + path,
    );
  }

  for (const providerInfo of externalProviders.values()) {
    const moduleInfo = modules.get(providerInfo.moduleName);
    if (!moduleInfo) {
      return err(
        "External provider '" +
          providerInfo.path +
          "' requires a matching '.tuff' contract file for module '" +
          providerInfo.moduleName +
          "'",
      );
    }

    moduleInfo.externalProvider = providerInfo;
  }

  return ok(modules);
}

export function populateProjectModuleDependencies(
  modules: Map<string, ModuleCompilationInfo>,
): Result<void, string> {
  for (const moduleInfo of modules.values()) {
    const tokenResult = tokenizeProjectModule(moduleInfo);
    if (!tokenResult.ok) {
      return tokenResult;
    }

    moduleInfo.dependencies = collectProjectModuleReferencesFromTokens(
      tokenResult.value,
      modules,
    ).filter((dependency) => dependency !== moduleInfo.moduleName);
  }

  return ok(undefined);
}

export function collectReachableModules(
  entryModule: string,
  modules: Map<string, ModuleCompilationInfo>,
): Result<Map<string, ModuleCompilationInfo>, string> {
  const reachable = new Map<string, ModuleCompilationInfo>();
  const visiting = new Set<string>();

  const visit = (moduleName: string): Result<void, string> => {
    const moduleInfo = modules.get(moduleName);
    if (!moduleInfo) {
      return err("Unknown module '" + moduleName + "'");
    }
    if (reachable.has(moduleName)) {
      return ok(undefined);
    }
    if (visiting.has(moduleName)) {
      return err(
        "Circular module dependency detected involving '" + moduleName + "'",
      );
    }

    visiting.add(moduleName);
    for (const dependency of moduleInfo.dependencies) {
      const dependencyResult = visit(dependency);
      if (!dependencyResult.ok) {
        return dependencyResult;
      }
    }
    visiting.delete(moduleName);

    reachable.set(moduleName, moduleInfo);
    return ok(undefined);
  };

  const visitResult = visit(entryModule);
  if (!visitResult.ok) {
    return visitResult;
  }

  return ok(reachable);
}

export function getProjectCompilationOrder(
  input: ProjectCompileInput,
): Result<ModuleCompilationInfo[], string> {
  const moduleRegistry = buildProjectModuleRegistry(
    input.files,
    getProjectTarget(input),
  );
  if (!moduleRegistry.ok) {
    return moduleRegistry;
  }

  const dependencyResult = populateProjectModuleDependencies(
    moduleRegistry.value,
  );
  if (!dependencyResult.ok) {
    return dependencyResult;
  }

  const reachable = collectReachableModules(
    input.entryModule,
    moduleRegistry.value,
  );
  if (!reachable.ok) {
    return reachable;
  }

  return ok(Array.from(reachable.value.values()));
}
