// Generated by scripts/refactor/split-compile.ts

import { err, ok } from "../../types";
import type { Result } from "../../types";
import type {
  Token,
  TokenizedCharLiteral,
  TokenizedStringLiteral,
} from "./ast";

export const VALID_TYPES = new Set([
  "U8",
  "U16",
  "U32",
  "U64",
  "USize",
  "I8",
  "I16",
  "I32",
  "I64",
  "ISize",
  "F32",
  "F64",
  "Char",
  "Bool",
  "Void",
]);

export function isWhitespace(char: string | undefined): boolean {
  return (
    char === " " ||
    char === "\t" ||
    char === "\n" ||
    char === "\r" ||
    char === "\v" ||
    char === "\f"
  );
}

export function isDigit(char: string | undefined): boolean {
  return char !== undefined && char >= "0" && char <= "9";
}

export function isLetter(char: string | undefined): boolean {
  return (
    (char !== undefined && char >= "a" && char <= "z") ||
    (char !== undefined && char >= "A" && char <= "Z")
  );
}

export function isPrimitiveNumericType(typeStr: string): boolean {
  return (
    VALID_TYPES.has(typeStr) &&
    typeStr !== "Bool" &&
    typeStr !== "Void" &&
    typeStr !== "Char"
  );
}

export function areTypesCompatible(
  expectedType: string,
  actualType: string,
): boolean {
  if (expectedType === actualType) {
    return true;
  }

  if (
    expectedType === "Bool" ||
    actualType === "Bool" ||
    expectedType === "Void" ||
    actualType === "Void" ||
    expectedType === "Char" ||
    actualType === "Char"
  ) {
    return false;
  }

  if (expectedType.startsWith("F") && actualType.startsWith("F")) {
    return true;
  }

  return (
    isPrimitiveNumericType(expectedType) && isPrimitiveNumericType(actualType)
  );
}

export function readEscapedCharValue(
  char: string | undefined,
): Result<number, string> {
  if (char === undefined) {
    return err("Unterminated character literal");
  }

  if (char === "n") return ok(10);
  if (char === "t") return ok(9);
  if (char === "r") return ok(13);
  if (char === "0") return ok(0);
  if (char === "'") return ok(39);
  if (char === '"') return ok(34);
  if (char === "\\") return ok(92);

  return err("Invalid escape sequence '\\" + char + "' in character literal");
}

export function tokenizeCharLiteral(
  input: string,
  startPos: number,
): Result<TokenizedCharLiteral, string> {
  const contentPos = startPos + 1;
  if (contentPos >= input.length) {
    return err("Unterminated character literal");
  }

  if (input[contentPos] === "'") {
    return err("Empty character literal is not allowed");
  }

  let charValue = 0;
  let nextPos = contentPos;

  if (input[nextPos] === "\\") {
    const escapedValue = readEscapedCharValue(input[nextPos + 1]);
    if (!escapedValue.ok) {
      return escapedValue;
    }
    charValue = escapedValue.value;
    nextPos += 2;
  } else {
    const codePoint = input.codePointAt(nextPos);
    if (codePoint === undefined) {
      return err("Unterminated character literal");
    }
    charValue = codePoint;
    nextPos += codePoint > 65535 ? 2 : 1;
  }

  if (nextPos >= input.length) {
    return err("Unterminated character literal");
  }

  if (input[nextPos] !== "'") {
    return err("Character literal must contain exactly one character");
  }

  return ok({
    token: { type: "CHAR", value: String(charValue) },
    nextPos: nextPos + 1,
  });
}

export function tokenizeStringLiteral(
  input: string,
  startPos: number,
): Result<TokenizedStringLiteral, string> {
  const codePoints: number[] = [];
  let pos = startPos + 1;

  while (pos < input.length) {
    const char = input[pos];
    if (char === '"') {
      return ok({
        token: { type: "STRING", value: codePoints },
        nextPos: pos + 1,
      });
    }

    if (char === "\\") {
      const escapedValue = readEscapedCharValue(input[pos + 1]);
      if (!escapedValue.ok) {
        return escapedValue;
      }
      codePoints.push(escapedValue.value);
      pos += 2;
      continue;
    }

    const codePoint = input.codePointAt(pos);
    if (codePoint === undefined) {
      return err("Unterminated string literal");
    }
    codePoints.push(codePoint);
    pos += codePoint > 65535 ? 2 : 1;
  }

  return err("Unterminated string literal");
}

export function validateType(typeStr: string): Result<undefined, string> {
  return VALID_TYPES.has(typeStr)
    ? ok(undefined)
    : err("Invalid type annotation: " + typeStr);
}

export function tokenize(input: string): Result<Token[], string> {
  const tokens: Token[] = [];
  let pos = 0;

  const lastToken = (): Token | undefined => {
    return tokens.length > 0 ? tokens[tokens.length - 1] : undefined;
  };

  const isOperatorContext = (): boolean => {
    const last = lastToken();
    return (
      last !== undefined &&
      (last.type === "NUMBER" ||
        last.type === "RPAREN" ||
        last.type === "RBRACKET" ||
        last.type === "IDENTIFIER" ||
        (last.type === "KEYWORD" && last.value === "this") ||
        last.type === "BOOL" ||
        last.type === "GT")
    );
  };

  while (pos < input.length) {
    const char = input[pos];

    // Skip whitespace
    if (isWhitespace(char)) {
      pos++;
      continue;
    }

    if (char === "'") {
      const charTokenResult = tokenizeCharLiteral(input, pos);
      if (!charTokenResult.ok) {
        return charTokenResult;
      }
      tokens.push(charTokenResult.value.token);
      pos = charTokenResult.value.nextPos;
      continue;
    }

    if (char === '"') {
      const stringTokenResult = tokenizeStringLiteral(input, pos);
      if (!stringTokenResult.ok) {
        return stringTokenResult;
      }
      tokens.push(stringTokenResult.value.token);
      pos = stringTokenResult.value.nextPos;
      continue;
    }

    // Operators (only if following a number or closing paren)
    if (char === "+" && isOperatorContext()) {
      // Check for +=
      if (pos + 1 < input.length && input[pos + 1] === "=") {
        tokens.push({ type: "PLUS_ASSIGN" });
        pos += 2;
      } else {
        tokens.push({ type: "OPERATOR", value: "+" });
        pos++;
      }
    } else if (char === "-" && isOperatorContext()) {
      // Check for -=
      if (pos + 1 < input.length && input[pos + 1] === "=") {
        tokens.push({ type: "MINUS_ASSIGN" });
        pos += 2;
      } else {
        tokens.push({ type: "OPERATOR", value: "-" });
        pos++;
      }
    } else if (char === "*") {
      // Handle * as either multiplication operator or dereference operator
      if (isOperatorContext()) {
        // Check for *=
        if (pos + 1 < input.length && input[pos + 1] === "=") {
          tokens.push({ type: "MULT_ASSIGN" });
          pos += 2;
        } else {
          tokens.push({ type: "OPERATOR", value: "*" });
          pos++;
        }
      } else {
        // * in prefix context is dereference operator (used in *y or pointer types *I32)
        tokens.push({ type: "OPERATOR", value: "*" });
        pos++;
      }
    } else if (char === "/" && isOperatorContext()) {
      // Check for /=
      if (pos + 1 < input.length && input[pos + 1] === "=") {
        tokens.push({ type: "DIV_ASSIGN" });
        pos += 2;
      } else {
        tokens.push({ type: "OPERATOR", value: "/" });
        pos++;
      }
    } else if (char === "%" && isOperatorContext()) {
      // Check for %=
      if (pos + 1 < input.length && input[pos + 1] === "=") {
        tokens.push({ type: "MOD_ASSIGN" });
        pos += 2;
      } else {
        tokens.push({ type: "OPERATOR", value: "%" });
        pos++;
      }
    } else if (char === "(") {
      tokens.push({ type: "LPAREN" });
      pos++;
    } else if (char === ")") {
      tokens.push({ type: "RPAREN" });
      pos++;
    } else if (char === "{") {
      tokens.push({ type: "LBRACE" });
      pos++;
    } else if (char === "}") {
      tokens.push({ type: "RBRACE" });
      pos++;
    } else if (char === "[") {
      tokens.push({ type: "LBRACKET" });
      pos++;
    } else if (char === "]") {
      tokens.push({ type: "RBRACKET" });
      pos++;
    } else if (char === "<") {
      // Check for <=
      if (pos + 1 < input.length && input[pos + 1] === "=") {
        tokens.push({ type: "COMPARISON", value: "<=" });
        pos += 2;
      } else {
        tokens.push({ type: "COMPARISON", value: "<" });
        pos++;
      }
    } else if (char === ">") {
      // Check for >=
      if (pos + 1 < input.length && input[pos + 1] === "=") {
        tokens.push({ type: "COMPARISON", value: ">=" });
        pos += 2;
      } else {
        tokens.push({ type: "COMPARISON", value: ">" });
        pos++;
      }
    } else if (char === ":") {
      if (pos + 1 < input.length && input[pos + 1] === ":") {
        tokens.push({ type: "DOUBLE_COLON" });
        pos += 2;
      } else {
        tokens.push({ type: "COLON" });
        pos++;
      }
    } else if (char === ";") {
      tokens.push({ type: "SEMICOLON" });
      pos++;
    } else if (char === ",") {
      tokens.push({ type: "COMMA" });
      pos++;
    } else if (char === ".") {
      tokens.push({ type: "DOT" });
      pos++;
    } else if (char === "=") {
      // Check for => (arrow)
      if (pos + 1 < input.length && input[pos + 1] === ">") {
        tokens.push({ type: "ARROW" });
        pos += 2;
      } else if (pos + 1 < input.length && input[pos + 1] === "=") {
        // Check for ==
        tokens.push({ type: "COMPARISON", value: "==" });
        pos += 2;
      } else {
        tokens.push({ type: "ASSIGN" });
        pos++;
      }
    } else if (char === "!") {
      // Check for !=
      if (pos + 1 < input.length && input[pos + 1] === "=") {
        tokens.push({ type: "COMPARISON", value: "!=" });
        pos += 2;
      } else {
        tokens.push({ type: "LOGICAL", value: "!" });
        pos++;
      }
    } else if (char === "&") {
      // Check for &&
      if (pos + 1 < input.length && input[pos + 1] === "&") {
        tokens.push({ type: "LOGICAL", value: "&&" });
        pos += 2;
      } else {
        // Single & is address-of operator
        tokens.push({ type: "ADDRESS_OF" });
        pos++;
      }
    } else if (char === "|") {
      // Check for ||
      if (pos + 1 < input.length && input[pos + 1] === "|") {
        tokens.push({ type: "LOGICAL", value: "||" });
        pos += 2;
      } else {
        tokens.push({ type: "PIPE" });
        pos++;
      }
    } else if (isLetter(char) || char === "_") {
      // Parse identifier (e.g., 'read', 'let', 'mut', type like 'U8', or wildcard '_')
      let ident = "";
      while (
        pos < input.length &&
        (isLetter(input[pos]) || isDigit(input[pos]) || input[pos] === "_")
      ) {
        ident += input[pos];
        pos++;
      }

      // Check if it's a keyword or boolean
      if (
        ident === "let" ||
        ident === "contract" ||
        ident === "extern" ||
        ident === "object" ||
        ident === "type" ||
        ident === "then" ||
        ident === "this" ||
        ident === "is" ||
        ident === "mut" ||
        ident === "if" ||
        ident === "else" ||
        ident === "while" ||
        ident === "break" ||
        ident === "continue" ||
        ident === "match" ||
        ident === "case" ||
        ident === "fn" ||
        ident === "return" ||
        ident === "struct"
      ) {
        tokens.push({ type: "KEYWORD", value: ident });
      } else if (ident === "true") {
        tokens.push({ type: "BOOL", value: "true" });
      } else if (ident === "false") {
        tokens.push({ type: "BOOL", value: "false" });
      } else {
        tokens.push({ type: "IDENTIFIER", value: ident });
      }
    } else if (isDigit(char) || (char === "-" && isDigit(input[pos + 1]))) {
      // Parse number with optional type and optional leading sign
      let numStr = "";

      // Handle optional negative sign
      if (char === "-") {
        numStr += "-";
        pos++;
      }

      // Parse digits
      while (pos < input.length && isDigit(input[pos])) {
        numStr += input[pos];
        pos++;
      }

      // Parse optional decimal point
      if (
        pos < input.length &&
        input[pos] === "." &&
        pos + 1 < input.length &&
        isDigit(input[pos + 1])
      ) {
        numStr += ".";
        pos++;

        while (pos < input.length && isDigit(input[pos])) {
          numStr += input[pos];
          pos++;
        }
      }

      // Parse optional type annotation
      if (pos < input.length && isLetter(input[pos])) {
        let typeStr = "";
        while (pos < input.length && isLetter(input[pos])) {
          typeStr += input[pos];
          pos++;
        }

        // Parse type numbers (e.g., U8, I32)
        while (pos < input.length && isDigit(input[pos])) {
          typeStr += input[pos];
          pos++;
        }

        const validateResult = validateType(typeStr);
        if (!validateResult.ok) {
          return validateResult;
        }

        numStr += typeStr;
      }

      tokens.push({ type: "NUMBER", value: numStr });
    } else {
      return err("Unexpected character: " + char);
    }
  }

  tokens.push({ type: "EOF" });
  return ok(tokens);
}
