// Generated by scripts/refactor/split-compile.ts

import { err, ok } from "../types";
import type { Result } from "../types";
import { codegenProgramReturn, generateStatementCode } from "./codegen";
import type { ASTNode, ModuleCompilationInfo, ModuleNode, Parser, ProjectCompileInput, ScopeFrame, Token } from "./core/ast";
import { createModuleResultName, getProjectCompilationOrder, tokenizeProjectModule } from "./core/project";
import { createScopeFrame, registerProjectModulesAsObjects } from "./core/scope";
import { tokenize } from "./core/tokenization";
import { collectTypeDeclarationNames, current, parseProgram, prescanFunctionSignatures, prescanStructDefinitions, prescanTypeAliases } from "./parser";
import { resolveTypeAliases, validateAST, validateStructSemantics } from "./semantics/validation";

export function createParser(
  tokens: Token[],
  currentScope: ScopeFrame,
  modules: Map<string, ModuleCompilationInfo> = new Map(),
): Parser {
  const parser: Parser = {
    tokens,
    pos: 0,
    variables: new Map(),
    functions: new Map(),
    modules,
    aliases: new Map(),
    aliasDeclarations: new Map(),
    structs: new Map(),
    structNames: new Set(),
    objects: new Map(),
    inLoop: false,
    currentFunctionReturnType: undefined,
    globalScope: currentScope,
    currentScope,
    provenConstraints: new Map(),
  };

  registerProjectModulesAsObjects(parser, modules);
  return parser;
}

export function prepareParser(parser: Parser): Result<void, string> {
  const typeNameCollectionResult = collectTypeDeclarationNames(parser);
  if (!typeNameCollectionResult.ok) {
    return typeNameCollectionResult;
  }

  const aliasPrescanResult = prescanTypeAliases(parser);
  if (!aliasPrescanResult.ok) {
    return aliasPrescanResult;
  }

  const aliasResolutionResult = resolveTypeAliases(parser);
  if (!aliasResolutionResult.ok) {
    return aliasResolutionResult;
  }

  const structPrescanResult = prescanStructDefinitions(parser);
  if (!structPrescanResult.ok) {
    return structPrescanResult;
  }

  return prescanFunctionSignatures(parser);
}

export function parseAndValidateProgram(parser: Parser): Result<ASTNode, string> {
  const prepared = prepareParser(parser);
  if (!prepared.ok) {
    return prepared;
  }

  const astResult = parseProgram(parser);
  if (!astResult.ok) {
    return astResult;
  }

  if (current(parser).type !== "EOF") {
    return err("Unexpected tokens after expression");
  }

  const ast = astResult.value;
  const validationResult = validateAST(ast);
  if (!validationResult.ok) {
    return validationResult;
  }

  const structSemanticsResult = validateStructSemantics(
    ast,
    parser.structs,
    parser.objects,
    new Map(),
  );
  if (!structSemanticsResult.ok) {
    return structSemanticsResult;
  }

  return ok(ast);
}

export function parseProjectModule(
  moduleInfo: ModuleCompilationInfo,
  modules: Map<string, ModuleCompilationInfo>,
): Result<ModuleNode, string> {
  const tokenResult = tokenizeProjectModule(moduleInfo);
  if (!tokenResult.ok) {
    return tokenResult;
  }

  const parser = createParser(tokenResult.value, moduleInfo.scope, modules);
  const astResult = parseAndValidateProgram(parser);
  if (!astResult.ok) {
    return err(
      "Module '" +
        moduleInfo.moduleName +
        "' failed to compile: " +
        astResult.error,
    );
  }

  const moduleAst: ModuleNode = {
    kind: "module",
    moduleName: moduleInfo.moduleName,
    runtimeName: moduleInfo.runtimeName,
    type: moduleInfo.typeName,
    body: astResult.value,
    scope: moduleInfo.scope,
  };

  moduleInfo.ast = moduleAst;
  return ok(moduleAst);
}

export function compile(input: string): Result<string, string> {
  const DEBUG = false; // Set to true to enable debug logging

  if (DEBUG) console.log("[COMPILE START]", input.substring(0, 100));

  if (input === "") {
    return ok("return 0;");
  }

  if (input !== input.trim()) {
    return err("Leading or trailing whitespace is not allowed");
  }

  if (DEBUG) console.log("[TOKENIZE]");
  const tokenResult = tokenize(input);
  if (!tokenResult.ok) {
    return tokenResult;
  }

  const parser = createParser(tokenResult.value, createScopeFrame(undefined));

  if (DEBUG) console.log("[PRESCAN]");
  if (DEBUG) console.log("[PARSE PROGRAM]");
  const astResult = parseAndValidateProgram(parser);
  if (!astResult.ok) {
    return astResult;
  }

  const ast = astResult.value;
  return ok(codegenProgramReturn(ast));
}

export function compileProject(
  input: ProjectCompileInput,
): Result<string, string> {
  const compilationOrder = getProjectCompilationOrder(
    input.entryModule,
    input.files,
  );
  if (!compilationOrder.ok) {
    return compilationOrder;
  }

  const reachableModules = new Map(
    compilationOrder.value.map((moduleInfo) => [
      moduleInfo.moduleName,
      moduleInfo,
    ]),
  );

  const moduleNodes: ModuleNode[] = [];
  for (const moduleInfo of compilationOrder.value) {
    const moduleAst = parseProjectModule(moduleInfo, reachableModules);
    if (!moduleAst.ok) {
      return moduleAst;
    }
    moduleNodes.push(moduleAst.value);
  }

  const entryModule = compilationOrder.value.find(
    (moduleInfo) => moduleInfo.moduleName === input.entryModule,
  );
  if (!entryModule) {
    return err("Unknown module '" + input.entryModule + "'");
  }

  const moduleCode = generateStatementCode(moduleNodes);
  return ok(
    moduleCode +
      " return " +
      createModuleResultName(entryModule.runtimeName) +
      ";",
  );
}

export const compileTuffToJS = compile;