// Generated by scripts/refactor/split-compile.ts

import { err, ok } from "../types";
import type { Result } from "../types";
import {
  codegenExternalProviderHelpers,
  codegenExternalProviderLoad,
  codegenProgramReturn,
  generateStatementCode,
} from "./codegen";
import type {
  ASTNode,
  ExternBindingInfo,
  ModuleCompilationInfo,
  ModuleImplementationOrigin,
  ModuleNode,
  Parser,
  ProjectCompileInput,
  ScopeFrame,
  Token,
} from "./core/ast";
import {
  createModuleResultName,
  getProjectCompilationOrder,
  tokenizeProjectModule,
} from "./core/project";
import {
  createScopeFrame,
  registerProjectModulesAsObjects,
} from "./core/scope";
import { tokenize } from "./core/tokenization";
import {
  collectTypeDeclarationNames,
  current,
  parseProgram,
  prescanFunctionSignatures,
  prescanStructDefinitions,
  prescanTypeAliases,
} from "./parser";
import {
  resolveTypeAliases,
  validateAST,
  validateStructSemantics,
} from "./semantics/validation";

export interface ModuleExternMetadata {
  externModuleName: string | undefined;
  externBindings: ExternBindingInfo[];
  implementationOrigin: ModuleImplementationOrigin;
}

export function createParser(
  tokens: Token[],
  currentScope: ScopeFrame,
  modules: Map<string, ModuleCompilationInfo> = new Map(),
  currentModuleName: string | undefined = undefined,
): Parser {
  const parser: Parser = {
    tokens,
    pos: 0,
    variables: new Map(),
    functions: new Map(),
    modules,
    aliases: new Map(),
    aliasDeclarations: new Map(),
    structs: new Map(),
    structNames: new Set(),
    objects: new Map(),
    inLoop: false,
    currentFunctionReturnType: undefined,
    globalScope: currentScope,
    currentScope,
    currentModuleName,
    provenConstraints: new Map(),
  };

  registerProjectModulesAsObjects(parser, modules);
  return parser;
}

export function prepareParser(parser: Parser): Result<void, string> {
  const typeNameCollectionResult = collectTypeDeclarationNames(parser);
  if (!typeNameCollectionResult.ok) {
    return typeNameCollectionResult;
  }

  const aliasPrescanResult = prescanTypeAliases(parser);
  if (!aliasPrescanResult.ok) {
    return aliasPrescanResult;
  }

  const aliasResolutionResult = resolveTypeAliases(parser);
  if (!aliasResolutionResult.ok) {
    return aliasResolutionResult;
  }

  const structPrescanResult = prescanStructDefinitions(parser);
  if (!structPrescanResult.ok) {
    return structPrescanResult;
  }

  return prescanFunctionSignatures(parser);
}

export function parseAndValidateProgram(
  parser: Parser,
): Result<ASTNode, string> {
  const prepared = prepareParser(parser);
  if (!prepared.ok) {
    return prepared;
  }

  const astResult = parseProgram(parser);
  if (!astResult.ok) {
    return astResult;
  }

  if (current(parser).type !== "EOF") {
    return err("Unexpected tokens after expression");
  }

  const ast = astResult.value;
  const validationResult = validateAST(ast);
  if (!validationResult.ok) {
    return validationResult;
  }

  const structSemanticsResult = validateStructSemantics(
    ast,
    parser.structs,
    parser.objects,
    new Map(),
  );
  if (!structSemanticsResult.ok) {
    return structSemanticsResult;
  }

  return ok(ast);
}

export function getTopLevelStatements(node: ASTNode): ASTNode[] {
  return node.kind === "block" ? node.statements : [];
}

export function collectModuleExternMetadata(
  moduleInfo: ModuleCompilationInfo,
  ast: ASTNode,
): Result<ModuleExternMetadata, string> {
  let externModuleName: string | undefined;
  const externBindings: ExternBindingInfo[] = [];
  let hasRuntimeTuffStatements = false;

  for (const statement of getTopLevelStatements(ast)) {
    if (statement.kind === "extern-module") {
      if (externModuleName) {
        return err(
          "Module '" +
            moduleInfo.moduleName +
            "' has multiple extern module declarations",
        );
      }
      externModuleName = statement.moduleName;
      continue;
    }

    if (statement.kind === "extern-function") {
      externBindings.push({ name: statement.name, kind: "function" });
      continue;
    }

    if (statement.kind === "extern-let") {
      externBindings.push({ name: statement.name, kind: "value" });
      continue;
    }

    if (
      statement.kind === "extern-type" ||
      statement.kind === "type-alias" ||
      statement.kind === "struct"
    ) {
      continue;
    }

    hasRuntimeTuffStatements = true;
  }

  if (externBindings.length > 0 && !externModuleName) {
    return err(
      "Module '" +
        moduleInfo.moduleName +
        "' must declare 'extern " +
        moduleInfo.moduleName +
        ";' before extern members",
    );
  }

  return ok({
    externModuleName,
    externBindings,
    implementationOrigin: externModuleName
      ? hasRuntimeTuffStatements
        ? "hybrid"
        : "external"
      : "tuff",
  });
}

export function parseProjectModule(
  moduleInfo: ModuleCompilationInfo,
  modules: Map<string, ModuleCompilationInfo>,
): Result<ModuleNode, string> {
  const tokenResult = tokenizeProjectModule(moduleInfo);
  if (!tokenResult.ok) {
    return tokenResult;
  }

  const parser = createParser(
    tokenResult.value,
    moduleInfo.scope,
    modules,
    moduleInfo.moduleName,
  );
  const astResult = parseAndValidateProgram(parser);
  if (!astResult.ok) {
    return err(
      "Module '" +
        moduleInfo.moduleName +
        "' failed to compile: " +
        astResult.error,
    );
  }

  const externMetadata = collectModuleExternMetadata(
    moduleInfo,
    astResult.value,
  );
  if (!externMetadata.ok) {
    return err(
      "Module '" +
        moduleInfo.moduleName +
        "' failed to compile: " +
        externMetadata.error,
    );
  }

  moduleInfo.externModuleName = externMetadata.value.externModuleName;
  moduleInfo.externBindings = externMetadata.value.externBindings;
  moduleInfo.implementationOrigin = externMetadata.value.implementationOrigin;

  if (moduleInfo.externModuleName && !moduleInfo.externalProvider) {
    return err(
      "Module '" +
        moduleInfo.moduleName +
        "' requires a companion '.js' provider",
    );
  }

  const moduleAst: ModuleNode = {
    kind: "module",
    moduleName: moduleInfo.moduleName,
    runtimeName: moduleInfo.runtimeName,
    type: moduleInfo.typeName,
    body: astResult.value,
    scope: moduleInfo.scope,
    implementationOrigin: moduleInfo.implementationOrigin,
    externalProviderVar: moduleInfo.externalProvider?.runtimeName,
    externBindings: moduleInfo.externBindings,
  };

  moduleInfo.ast = moduleAst;
  return ok(moduleAst);
}

export function compile(input: string): Result<string, string> {
  const DEBUG = false; // Set to true to enable debug logging

  if (DEBUG) console.log("[COMPILE START]", input.substring(0, 100));

  if (input === "") {
    return ok("return 0;");
  }

  if (input !== input.trim()) {
    return err("Leading or trailing whitespace is not allowed");
  }

  if (DEBUG) console.log("[TOKENIZE]");
  const tokenResult = tokenize(input);
  if (!tokenResult.ok) {
    return tokenResult;
  }

  const parser = createParser(tokenResult.value, createScopeFrame(undefined));

  if (DEBUG) console.log("[PRESCAN]");
  if (DEBUG) console.log("[PARSE PROGRAM]");
  const astResult = parseAndValidateProgram(parser);
  if (!astResult.ok) {
    return astResult;
  }

  const ast = astResult.value;
  return ok(codegenProgramReturn(ast));
}

export function compileProject(
  input: ProjectCompileInput,
): Result<string, string> {
  const compilationOrder = getProjectCompilationOrder(input);
  if (!compilationOrder.ok) {
    return compilationOrder;
  }

  const reachableModules = new Map(
    compilationOrder.value.map((moduleInfo) => [
      moduleInfo.moduleName,
      moduleInfo,
    ]),
  );

  const moduleNodes: ModuleNode[] = [];
  for (const moduleInfo of compilationOrder.value) {
    const moduleAst = parseProjectModule(moduleInfo, reachableModules);
    if (!moduleAst.ok) {
      return moduleAst;
    }
    moduleNodes.push(moduleAst.value);
  }

  const entryModule = compilationOrder.value.find(
    (moduleInfo) => moduleInfo.moduleName === input.entryModule,
  );
  if (!entryModule) {
    return err("Unknown module '" + input.entryModule + "'");
  }

  const externalProviderModules = compilationOrder.value.filter(
    (moduleInfo) => moduleInfo.externModuleName && moduleInfo.externalProvider,
  );
  const externalPrelude =
    externalProviderModules.length > 0
      ? codegenExternalProviderHelpers() +
        " " +
        externalProviderModules
          .map((moduleInfo) =>
            codegenExternalProviderLoad(
              moduleInfo.externalProvider?.runtimeName ?? "",
              moduleInfo.externalProvider?.source ?? "",
            ),
          )
          .join(" ") +
        " "
      : "";

  const moduleCode = generateStatementCode(moduleNodes);
  return ok(
    externalPrelude +
      moduleCode +
      " return " +
      createModuleResultName(entryModule.runtimeName) +
      ";",
  );
}

export const compileTuffToJS = compile;
