// Generated by scripts/refactor/split-compile.ts

import { err, ok } from "../../types";
import type { Result } from "../../types";
import type {
  ASTNode,
  FunctionParameter,
  MatchCase,
  ScopeFrame,
} from "../core/ast";
import { createModuleResultName } from "../core/project";
import { isDigit } from "../core/tokenization";

export function codegenProgramReturn(node: ASTNode): string {
  const code = codegenAST(node);
  return node.kind === "block" ? code + ";" : "return " + code + ";";
}

export function codegenProgramEvaluation(
  node: ASTNode,
  resultName: string,
): string {
  if (node.kind === "block") {
    return (
      generateStatementCode(node.statements) +
      " " +
      resultName +
      " = " +
      codegenAST(node.result) +
      ";"
    );
  }

  return resultName + " = " + codegenAST(node) + ";";
}

export function codegenFunctionLikeDeclaration(
  name: string | undefined,
  parameters: FunctionParameter[],
  returnType: string,
  body: ASTNode,
): string {
  const paramList = parameters
    .map((parameter) => String(parameter.name))
    .join(", ");
  const bodyCode = codegenFunctionLikeBody(body, returnType);
  const functionName = name ? " " + name : "";
  const suffix = name ? ";" : "";
  return (
    "function" +
    functionName +
    "(" +
    paramList +
    ") { " +
    bodyCode +
    " }" +
    suffix
  );
}

export function codegenFunctionLikeBody(
  body: ASTNode,
  returnType: string,
): string {
  let bodyCode = "";

  if (body.kind === "block") {
    const statements = body.statements;
    bodyCode = generateStatementCode(statements);
    const lastStmt =
      statements.length > 0 ? statements[statements.length - 1] : undefined;
    if (!(lastStmt && lastStmt.kind === "return")) {
      if (returnType === "Void") {
        if (body.result.kind !== "number" || body.result.value !== "0") {
          bodyCode += codegenAST(body.result);
        }
      } else {
        bodyCode += "return " + codegenAST(body.result);
      }
    }
    return bodyCode;
  }

  if (returnType === "Void") {
    return codegenAST(body);
  }

  return "return " + codegenAST(body);
}

export function extractNumberValue(numericLiteral: string): string {
  let pos = 0;
  let result = "";

  // Handle optional sign
  if (pos < numericLiteral.length && numericLiteral[pos] === "-") {
    result += "-";
    pos++;
  }

  // Extract digits
  while (pos < numericLiteral.length && isDigit(numericLiteral[pos])) {
    result += numericLiteral[pos];
    pos++;
  }

  // Extract optional decimal part
  if (pos < numericLiteral.length && numericLiteral[pos] === ".") {
    result += ".";
    pos++;

    while (pos < numericLiteral.length && isDigit(numericLiteral[pos])) {
      result += numericLiteral[pos];
      pos++;
    }
  }

  return result || "0";
}

export function getTypeFromLiteral(numericLiteral: string): string | undefined {
  let pos = 0;

  // Skip sign and digits
  if (pos < numericLiteral.length && numericLiteral[pos] === "-") {
    pos++;
  }

  while (pos < numericLiteral.length && isDigit(numericLiteral[pos])) {
    pos++;
  }

  // Skip decimal if present
  if (pos < numericLiteral.length && numericLiteral[pos] === ".") {
    pos++;

    while (pos < numericLiteral.length && isDigit(numericLiteral[pos])) {
      pos++;
    }
  }

  // Extract type
  if (pos < numericLiteral.length) {
    return numericLiteral.substring(pos);
  }

  return undefined;
}

export function validateNegativeType(
  literal: string,
): Result<undefined, string> {
  if (!literal.startsWith("-")) {
    return ok(undefined);
  }

  const type = getTypeFromLiteral(literal);
  if (type && !type.startsWith("I") && !type.startsWith("F")) {
    return err("Cannot apply negative sign to unsigned type: " + literal);
  }

  return ok(undefined);
}

export function generateStatementCode(statements: ASTNode[]): string {
  return statements
    .map((stmt) => {
      const code = codegenAST(stmt);
      return code.endsWith(";") ? code : code + ";";
    })
    .join(" ");
}

export function codegenThisScopeObject(scope: ScopeFrame): string {
  const parentExpression = scope.parent
    ? codegenThisScopeObject(scope.parent)
    : undefined;

  const memberDefinitions: string[] = [];
  const emittedMembers = new Set<string>();
  for (const [name, binding] of scope.members) {
    emittedMembers.add(name);
    if (binding.kind === "function") {
      memberDefinitions.push("get " + name + "() { return " + name + "; }");
      continue;
    }

    memberDefinitions.push("get " + name + "() { return " + name + "; }");
    if (binding.assignable) {
      memberDefinitions.push(
        "set " + name + "(_tuffValue) { " + name + " = _tuffValue; }",
      );
    }
  }

  if (scope.parent?.kind === "object") {
    for (const [name, binding] of scope.parent.members) {
      if (emittedMembers.has(name)) {
        continue;
      }

      if (binding.kind === "function") {
        memberDefinitions.push(
          "get " + name + "() { return _tuffParent." + name + "; }",
        );
        continue;
      }

      memberDefinitions.push(
        "get " + name + "() { return _tuffParent." + name + "; }",
      );
      if (binding.assignable) {
        memberDefinitions.push(
          "set " +
            name +
            "(_tuffValue) { _tuffParent." +
            name +
            " = _tuffValue; }",
        );
      }
    }
  }

  memberDefinitions.push(
    scope.parent
      ? "get this() { return _tuffParent; }"
      : "get this() { return _tuffThis; }",
  );

  const parentInit = scope.parent
    ? " const _tuffParent = " + parentExpression + ";"
    : "";

  return (
    "(() => {" +
    parentInit +
    " const _tuffThis = { " +
    memberDefinitions.join(", ") +
    " }; return _tuffThis; })()"
  );
}

export function codegenAST(node: ASTNode): string {
  if (node.kind === "number") {
    // Extract numeric part, stripping type annotation
    return extractNumberValue(node.value);
  }

  if (node.kind === "string") {
    return "[" + node.value.join(", ") + "]";
  }

  if (node.kind === "char") {
    return node.value;
  }

  if (node.kind === "boolean") {
    // Convert boolean to number (1 for true, 0 for false)
    return node.value ? "1" : "0";
  }

  if (node.kind === "is") {
    if (node.runtimeCheck) {
      const expression =
        node.expression.kind === "variable"
          ? node.expression.name
          : codegenAST(node.expression);
      return (
        "(() => { const _tuffValue = " +
        expression +
        '; return _tuffValue && _tuffValue.__tuffUnion && _tuffValue.tag === "' +
        node.checkedType +
        '" ? 1 : 0; })()'
      );
    }
    return node.matches ? "1" : "0";
  }

  if (node.kind === "union-wrap") {
    const expression = codegenAST(node.expression);
    return (
      '({ __tuffUnion: true, tag: "' +
      node.armType +
      '", value: ' +
      expression +
      " })"
    );
  }

  if (node.kind === "read") {
    return "readValue()";
  }

  if (node.kind === "module-reference") {
    return node.runtimeName;
  }

  if (node.kind === "variable") {
    return (
      "(() => { const _tuffValue = " +
      node.name +
      "; return _tuffValue && _tuffValue.__tuffUnion ? _tuffValue.value : _tuffValue; })()"
    );
  }

  if (node.kind === "this") {
    return codegenThisScopeObject(node.scope);
  }

  if (node.kind === "let") {
    const init = codegenAST(node.initializer);
    return "let " + node.name + " = " + init;
  }

  if (node.kind === "destructure") {
    return generateStatementCode(node.statements);
  }

  if (node.kind === "assign") {
    const value = codegenAST(node.value);
    return node.name + " = " + value;
  }

  if (node.kind === "deref-assign") {
    const value = codegenAST(node.value);
    // If we know which variable the pointer points to, assign to that variable
    if (node.targetVar) {
      return node.targetVar + " = " + value;
    }
    // Otherwise, fall back to assigning through the pointer
    const target = codegenAST(node.target);
    return target + " = " + value;
  }

  if (
    node.kind === "binary" ||
    node.kind === "comparison" ||
    node.kind === "logical"
  ) {
    const left = codegenAST(node.left);
    const right = codegenAST(node.right);
    // For division with integer types, use Math.trunc for integer division
    if (node.kind === "binary" && node.operator === "/") {
      return "(Math.trunc(" + left + " / " + right + "))";
    }
    return "(" + left + " " + node.operator + " " + right + ")";
  }

  if (node.kind === "unary-logical") {
    const operand = codegenAST(node.operand);
    return "(!" + operand + ")";
  }

  if (node.kind === "unary-op") {
    if (node.operator === "*") {
      const operand = codegenAST(node.operand);
      // Dereference: *ptr -> ptr (in a simple interpreter, values are already dereferenced)
      return operand;
    } else if (node.operator === "&" || node.operator === "&mut") {
      if (node.operand.kind === "array-slice") {
        return codegenAST(node.operand);
      }

      const operand = codegenAST(node.operand);
      // Address-of: &x -> x (in our simple model, we just return the variable/value)
      return operand;
    }
  }

  if (node.kind === "block") {
    const statements = generateStatementCode(node.statements);
    const result = codegenAST(node.result);
    return statements + " return " + result;
  }

  if (node.kind === "if") {
    const condition = codegenAST(node.condition);

    let thenCode = "";
    if (node.thenBranch.kind === "block") {
      // Check if block has a meaningful final expression (not just 0)
      const hasResult =
        node.thenBranch.result &&
        !(
          node.thenBranch.result.kind === "number" &&
          node.thenBranch.result.value === "0"
        );

      const stmtCode = generateStatementCode(node.thenBranch.statements);
      if (hasResult && node.elseBranch) {
        // Block with meaningful result and there's an else - it's an expression
        const resultCode = codegenAST(node.thenBranch.result);
        thenCode = stmtCode + " return " + resultCode;
      } else {
        // Just statements, no meaningful result
        thenCode = stmtCode;
      }
    } else {
      thenCode = codegenAST(node.thenBranch);
    }

    if (node.elseBranch === undefined) {
      // if without else - used as statement
      return "if (" + condition + ") { " + thenCode + " }";
    }

    // if with else - generate else branch code
    let elseCode = "";
    if (node.elseBranch.kind === "block") {
      // Check if block has a meaningful final expression
      const hasResult =
        node.elseBranch.result &&
        !(
          node.elseBranch.result.kind === "number" &&
          node.elseBranch.result.value === "0"
        );

      const stmtCode = generateStatementCode(node.elseBranch.statements);
      if (hasResult) {
        const resultCode = codegenAST(node.elseBranch.result);
        elseCode = stmtCode + " return " + resultCode;
      } else {
        elseCode = stmtCode;
      }
    } else if (node.elseBranch.kind === "if") {
      // else if - the recursive call will generate the correct syntax
      // For nested if nodes, we need to generate them as expressions if blocks are involved
      const innerIfCode = codegenAST(node.elseBranch);

      if (node.thenBranch.kind === "block") {
        // Then has statements, use if/else syntax
        return (
          "if (" + condition + ") { " + thenCode + " } else " + innerIfCode
        );
      } else {
        // Both are non-block expressions, so treat as full ternary
        return "(" + condition + " ? " + thenCode + " : " + innerIfCode + ")";
      }
    } else {
      elseCode = codegenAST(node.elseBranch);
    }

    // Check if both branches are simple expressions without statements or blocks
    if (node.thenBranch.kind !== "block" && node.elseBranch.kind !== "block") {
      // Both are simple expressions - use ternary
      return "(" + condition + " ? " + thenCode + " : " + elseCode + ")";
    } else {
      // At least one has statements - need to wrap as expression
      // Use IIFE to convert if statement to expression
      return (
        "(function() { if (" +
        condition +
        ") { " +
        thenCode +
        " } else { " +
        elseCode +
        " } }())"
      );
    }
  }

  if (node.kind === "while") {
    const condition = codegenAST(node.condition);
    let bodyCode = "";

    if (node.body.kind === "block") {
      bodyCode = generateStatementCode(node.body.statements);
    } else {
      bodyCode = codegenAST(node.body);
    }

    return "while (" + condition + ") { " + bodyCode + " }";
  }

  if (node.kind === "break") {
    return "break";
  }

  if (node.kind === "continue") {
    return "continue";
  }

  if (node.kind === "return") {
    const value = codegenAST(node.value);
    return "return " + value;
  }

  if (node.kind === "match") {
    const matchExpr = codegenAST(node.matchExpr);

    // Generate ternary chain for match cases
    // match (x) { case 1 => 10; case 2 => 20; case _ => 0; }
    // becomes: x === 1 ? 10 : x === 2 ? 20 : 0
    let result = "";
    let wildcardCase: MatchCase | undefined;
    const regularCases: MatchCase[] = [];

    for (const c of node.cases) {
      if (c.pattern.type === "wildcard") {
        wildcardCase = c;
      } else {
        regularCases.push(c);
      }
    }

    // Check if all non-wildcard cases are boolean (exhaustive boolean match)
    const isExhaustiveBooleanMatch =
      regularCases.length > 0 &&
      regularCases.every((c) => c.pattern.type === "boolean") &&
      regularCases.length === 2 &&
      regularCases.some((c) => (c.pattern as any).value === true) &&
      regularCases.some((c) => (c.pattern as any).value === false);

    // Build ternary chain for all cases
    if (isExhaustiveBooleanMatch) {
      // Special handling for exhaustive boolean: x === 1 ? trueValue : falseValue
      const trueCase = regularCases.find(
        (c) => (c.pattern as any).value === true,
      );
      const falseCase = regularCases.find(
        (c) => (c.pattern as any).value === false,
      );
      if (trueCase && falseCase) {
        const trueResult = codegenAST(trueCase.result);
        const falseResult = codegenAST(falseCase.result);
        result = matchExpr + " === 1 ? " + trueResult + " : " + falseResult;
      }
    } else {
      // Regular ternary chain
      regularCases.forEach((c, i) => {
        const caseResult = codegenAST(c.result);

        if (c.pattern.type === "literal") {
          result += matchExpr + " === " + c.pattern.value + " ? " + caseResult;
        } else if (c.pattern.type === "boolean") {
          result +=
            matchExpr + " === " + c.pattern.value
              ? "1"
              : "0" + " ? " + caseResult;
        }

        if (i < regularCases.length - 1 || wildcardCase) {
          result += " : ";
        }
      });

      // Add wildcard case at the end
      if (wildcardCase) {
        const wildcardResult = codegenAST(wildcardCase.result);
        result += wildcardResult;
      }
    }

    return "(" + result + ")";
  }

  if (node.kind === "function") {
    return codegenFunctionLikeDeclaration(
      node.name,
      node.parameters,
      node.returnType,
      node.body,
    );
  }

  if (node.kind === "object") {
    const statements = generateStatementCode(node.body);
    const runtimeObject = codegenThisScopeObject(node.scope);
    return (
      "const " +
      node.name +
      " = (() => { " +
      statements +
      " return " +
      runtimeObject +
      "; })()"
    );
  }

  if (node.kind === "module") {
    const runtimeObject = codegenThisScopeObject(node.scope);
    const resultName = createModuleResultName(node.runtimeName);
    return (
      "let " +
      resultName +
      "; const " +
      node.runtimeName +
      " = (() => { " +
      codegenProgramEvaluation(node.body, resultName) +
      " return " +
      runtimeObject +
      "; })()"
    );
  }

  if (node.kind === "type-alias") {
    return "0";
  }

  if (
    node.kind === "extern-module" ||
    node.kind === "extern-function" ||
    node.kind === "extern-let" ||
    node.kind === "extern-type"
  ) {
    return "0";
  }

  if (node.kind === "closure") {
    return codegenFunctionLikeDeclaration(
      undefined,
      node.parameters,
      node.returnType,
      node.body,
    );
  }

  if (node.kind === "function-call") {
    // Generate function call
    const argList = node.arguments.map((arg) => codegenAST(arg)).join(", ");

    return node.name + "(" + argList + ")";
  }

  if (node.kind === "call") {
    const callee = codegenAST(node.callee);
    const argList = node.arguments.map((arg) => codegenAST(arg)).join(", ");
    return callee + "(" + argList + ")";
  }

  if (node.kind === "struct") {
    // Struct declarations don't generate code themselves
    // They are just type definitions
    return "0";
  }

  if (node.kind === "struct-instantiation") {
    // Generate struct instantiation as JavaScript object
    const fields = node.fields
      .map((f) => {
        const value = codegenAST(f.value);
        return f.name + ": " + value;
      })
      .join(", ");

    return "{ " + fields + " }";
  }

  if (node.kind === "array-literal") {
    if (node.generator && node.repeatCount !== undefined) {
      const generator = codegenAST(node.generator);
      return (
        "(() => { const _tuffArray = []; const _tuffGenerator = (" +
        generator +
        "); for (let _tuffIndex = 0; _tuffIndex < " +
        node.repeatCount +
        "; _tuffIndex += 1) { _tuffArray.push(_tuffGenerator()); } return _tuffArray; })()"
      );
    }

    // Generate array literal as a JavaScript array.
    const elements = node.elements.map((elem) => codegenAST(elem));
    return "[" + elements.join(", ") + "]";
  }

  if (node.kind === "array-access") {
    const array = codegenAST(node.array);
    const index = codegenAST(node.index);
    return (
      "(() => { const _tuffArray = " +
      array +
      "; const _tuffIndex = " +
      index +
      "; return _tuffArray && _tuffArray.__tuffSlice ? _tuffArray.data[_tuffArray.start + _tuffIndex] : _tuffArray[_tuffIndex]; })()"
    );
  }

  if (node.kind === "array-slice") {
    const array = codegenAST(node.array);
    return (
      "(() => { const _tuffArray = " +
      array +
      "; const _tuffBase = _tuffArray && _tuffArray.__tuffSlice ? _tuffArray.data : _tuffArray; const _tuffStartOffset = _tuffArray && _tuffArray.__tuffSlice ? _tuffArray.start : 0; const _tuffStart = _tuffStartOffset + " +
      node.start +
      "; const _tuffEnd = _tuffStartOffset + " +
      node.end +
      "; return { __tuffSlice: true, data: _tuffBase, start: _tuffStart, end: _tuffEnd, length: _tuffEnd - _tuffStart }; })()"
    );
  }

  if (node.kind === "array-assign") {
    const array = codegenAST(node.array);
    const index = codegenAST(node.index);
    const value = codegenAST(node.value);
    return (
      "(() => { const _tuffArray = " +
      array +
      "; const _tuffIndex = " +
      index +
      "; const _tuffValue = " +
      value +
      "; if (_tuffArray && _tuffArray.__tuffSlice) { _tuffArray.data[_tuffArray.start + _tuffIndex] = _tuffValue; } else { _tuffArray[_tuffIndex] = _tuffValue; } return _tuffValue; })()"
    );
  }

  if (node.kind === "field-access") {
    // Generate field access
    const obj = codegenAST(node.object);
    return obj + "." + node.fieldName;
  }

  if (node.kind === "field-assign") {
    // Generate field assignment
    const obj = codegenAST(node.object);
    const value = codegenAST(node.value);
    return obj + "." + node.fieldName + " = " + value;
  }

  return "0";
}
