// Generated by scripts/refactor/split-compile.ts

import { err, ok } from "../../types";
import type { Result } from "../../types";
import type {
  ASTNode,
  ComparisonNode,
  EvaluationResult,
  FunctionInfo,
  FunctionParameter,
  LogicalNode,
  NumberNode,
  ParsedFunctionType,
  Parser,
  RefinementConstraint,
  RefinementType,
  StructField,
  StructInfo,
  TypeNarrowingInfo,
  UnionWrapNode,
  VariableInfo,
  VariableNode,
} from "../core/ast";
import {
  findScopeBinding,
  resolveThisMemberAccess,
  resolveThisScopeNode,
  validateThisScopeAgainstStruct,
} from "../core/scope";
import {
  areTypesCompatible,
  isDigit,
  isLetter,
  VALID_TYPES,
} from "../core/tokenization";
import {
  getArrayLikeInfo,
  inferZeroArgCallableReturnType,
  parseArrayType,
  parseFunctionTypeString,
  parseSliceType,
  parseUnionTypeString,
} from "../parser";

export function validateTypeWithStructs(
  parser: Parser,
  typeStr: string,
): Result<undefined, string> {
  return isKnownNamedType(parser, typeStr)
    ? ok(undefined)
    : err("Invalid type annotation: " + typeStr);
}

export function splitTopLevel(text: string, separator: string): string[] {
  const parts: string[] = [];
  let currentPart = "";
  let parenDepth = 0;
  let bracketDepth = 0;
  let angleDepth = 0;

  for (const char of text) {
    if (char === "(") {
      parenDepth++;
    } else if (char === ")") {
      parenDepth--;
    } else if (char === "[") {
      bracketDepth++;
    } else if (char === "]") {
      bracketDepth--;
    } else if (char === "<") {
      angleDepth++;
    } else if (char === ">") {
      angleDepth--;
    }

    if (
      char === separator &&
      parenDepth === 0 &&
      bracketDepth === 0 &&
      angleDepth === 0
    ) {
      parts.push(currentPart.trim());
      currentPart = "";
    } else {
      currentPart += char;
    }
  }

  if (currentPart.trim().length > 0 || text.length === 0) {
    parts.push(currentPart.trim());
  }

  return parts;
}

export interface ParsedGenericTypeString {
  baseType: string;
  typeArguments: string[];
}

export function parseGenericTypeString(
  typeStr: string,
): ParsedGenericTypeString | undefined {
  const trimmed = typeStr.trim();
  const ltIndex = trimmed.indexOf("<");
  if (ltIndex <= 0 || !trimmed.endsWith(">")) {
    return undefined;
  }

  const baseType = trimmed.slice(0, ltIndex).trim();
  if (baseType.length === 0) {
    return undefined;
  }

  let angleDepth = 0;
  let closingIndex = -1;
  for (let i = ltIndex; i < trimmed.length; i++) {
    const char = trimmed[i];
    if (char === "<") {
      angleDepth++;
    } else if (char === ">") {
      angleDepth--;
      if (angleDepth === 0) {
        closingIndex = i;
        break;
      }
    }
  }

  if (closingIndex !== trimmed.length - 1) {
    return undefined;
  }

  const typeArgumentsText = trimmed.slice(ltIndex + 1, -1).trim();
  const typeArguments =
    typeArgumentsText.length === 0
      ? []
      : splitTopLevel(typeArgumentsText, ",").map((part) => part.trim());

  return {
    baseType,
    typeArguments,
  };
}

export function isGenericTypeParameter(
  parser: Parser,
  typeStr: string,
): boolean {
  return parser.genericTypeParameters.includes(typeStr);
}

export function createTypeParameterSubstitutions(
  typeParameters: string[],
  typeArguments: string[],
  subjectName: string,
  subjectKind: string,
): Result<Map<string, string>, string> {
  if (typeParameters.length !== typeArguments.length) {
    return err(
      subjectKind +
        " '" +
        subjectName +
        "' expects " +
        typeParameters.length +
        " type arguments, got " +
        typeArguments.length,
    );
  }

  const substitutions = new Map<string, string>();
  for (let i = 0; i < typeParameters.length; i++) {
    const typeParameter = typeParameters[i];
    const typeArgument = typeArguments[i];
    if (typeParameter && typeArgument) {
      substitutions.set(typeParameter, typeArgument);
    }
  }

  return ok(substitutions);
}

export function rewriteCompositeType(
  parser: Parser,
  typeStr: string,
  leafMapper: CallableFunction,
  genericMapper?: CallableFunction,
): Result<string, string> {
  if (typeStr.startsWith("*mut ")) {
    const innerType = rewriteCompositeType(
      parser,
      typeStr.slice(5),
      leafMapper,
      genericMapper,
    );
    return innerType.ok ? ok("*mut " + innerType.value) : innerType;
  }

  if (typeStr.startsWith("*")) {
    const innerType = rewriteCompositeType(
      parser,
      typeStr.slice(1),
      leafMapper,
      genericMapper,
    );
    return innerType.ok ? ok("*" + innerType.value) : innerType;
  }

  const arrayType = parseArrayType(typeStr);
  if (arrayType) {
    const elementType = rewriteCompositeType(
      parser,
      arrayType.elementType,
      leafMapper,
      genericMapper,
    );
    return elementType.ok
      ? ok("[" + elementType.value + ";" + arrayType.length + "]")
      : elementType;
  }

  const sliceType = parseSliceType(typeStr);
  if (sliceType) {
    const elementType = rewriteCompositeType(
      parser,
      sliceType.elementType,
      leafMapper,
      genericMapper,
    );
    return elementType.ok ? ok("[" + elementType.value + "]") : elementType;
  }

  const functionType = parseFunctionTypeString(typeStr);
  if (functionType) {
    const parameterTypes: string[] = [];
    for (const parameterType of functionType.parameterTypes) {
      const mappedParameterType = rewriteCompositeType(
        parser,
        parameterType,
        leafMapper,
        genericMapper,
      );
      if (!mappedParameterType.ok) {
        return mappedParameterType;
      }
      parameterTypes.push(mappedParameterType.value);
    }

    const returnType = rewriteCompositeType(
      parser,
      functionType.returnType,
      leafMapper,
      genericMapper,
    );
    if (!returnType.ok) {
      return returnType;
    }

    return ok(formatFunctionType(parameterTypes, returnType.value));
  }

  const unionTypeArms = parseUnionTypeString(typeStr);
  if (unionTypeArms) {
    const mappedArms: string[] = [];
    for (const arm of unionTypeArms) {
      const mappedArm = rewriteCompositeType(
        parser,
        arm,
        leafMapper,
        genericMapper,
      );
      if (!mappedArm.ok) {
        return mappedArm;
      }
      mappedArms.push(mappedArm.value);
    }

    return ok(joinUnionTypeArms(mappedArms));
  }

  const genericType = parseGenericTypeString(typeStr);
  if (genericType) {
    const mappedTypeArguments: string[] = [];
    for (const typeArgument of genericType.typeArguments) {
      const mappedTypeArgument = rewriteCompositeType(
        parser,
        typeArgument,
        leafMapper,
        genericMapper,
      );
      if (!mappedTypeArgument.ok) {
        return mappedTypeArgument;
      }
      mappedTypeArguments.push(mappedTypeArgument.value);
    }

    return genericMapper
      ? (genericMapper(genericType.baseType, mappedTypeArguments) as Result<
          string,
          string
        >)
      : ok(genericType.baseType + "<" + mappedTypeArguments.join(", ") + ">");
  }

  return leafMapper(typeStr) as Result<string, string>;
}

export function substituteTypeParameters(
  parser: Parser,
  typeStr: string,
  substitutions: Map<string, string>,
): Result<string, string> {
  const directSubstitution = substitutions.get(typeStr);
  if (directSubstitution) {
    return ok(directSubstitution);
  }

  return rewriteCompositeType(parser, typeStr, (typeName: string) =>
    ok(substitutions.get(typeName) ?? typeName),
  );
}

export function inferTypeParameterBindings(
  parser: Parser,
  patternType: string,
  actualType: string,
  bindings: Map<string, string>,
): Result<void, string> {
  if (isGenericTypeParameter(parser, patternType)) {
    const existingBinding = bindings.get(patternType);
    if (!existingBinding) {
      bindings.set(patternType, actualType);
      return ok(undefined);
    }

    return existingBinding === actualType
      ? ok(undefined)
      : err(
          "Type inference conflict: generic parameter '" +
            patternType +
            "' matched both '" +
            existingBinding +
            "' and '" +
            actualType +
            "'",
        );
  }

  if (patternType === actualType) {
    return ok(undefined);
  }

  if (patternType.startsWith("*mut ") && actualType.startsWith("*mut ")) {
    return inferTypeParameterBindings(
      parser,
      patternType.slice(5),
      actualType.slice(5),
      bindings,
    );
  }

  if (patternType.startsWith("*") && actualType.startsWith("*")) {
    const normalizedPattern = patternType.startsWith("*mut ")
      ? patternType.slice(5)
      : patternType.slice(1);
    const normalizedActual = actualType.startsWith("*mut ")
      ? actualType.slice(5)
      : actualType.slice(1);
    return inferTypeParameterBindings(
      parser,
      normalizedPattern,
      normalizedActual,
      bindings,
    );
  }

  const patternArray = parseArrayType(patternType);
  const actualArray = parseArrayType(actualType);
  if (patternArray && actualArray) {
    if (patternArray.length !== actualArray.length) {
      return err(
        "Type inference mismatch: expected array length " +
          patternArray.length +
          " but got " +
          actualArray.length,
      );
    }
    return inferTypeParameterBindings(
      parser,
      patternArray.elementType,
      actualArray.elementType,
      bindings,
    );
  }

  const patternSlice = parseSliceType(patternType);
  const actualSlice = parseSliceType(actualType);
  if (patternSlice && actualSlice) {
    return inferTypeParameterBindings(
      parser,
      patternSlice.elementType,
      actualSlice.elementType,
      bindings,
    );
  }

  const patternFunction = parseFunctionTypeString(patternType);
  const actualFunction = parseFunctionTypeString(actualType);
  if (patternFunction && actualFunction) {
    if (
      patternFunction.parameterTypes.length !==
      actualFunction.parameterTypes.length
    ) {
      return err("Type inference mismatch: function parameter count differs");
    }

    for (let i = 0; i < patternFunction.parameterTypes.length; i++) {
      const parameterBinding = inferTypeParameterBindings(
        parser,
        patternFunction.parameterTypes[i] ?? "",
        actualFunction.parameterTypes[i] ?? "",
        bindings,
      );
      if (!parameterBinding.ok) {
        return parameterBinding;
      }
    }

    return inferTypeParameterBindings(
      parser,
      patternFunction.returnType,
      actualFunction.returnType,
      bindings,
    );
  }

  const patternGeneric = parseGenericTypeString(patternType);
  const actualGeneric = parseGenericTypeString(actualType);
  if (patternGeneric && actualGeneric) {
    if (
      patternGeneric.baseType !== actualGeneric.baseType ||
      patternGeneric.typeArguments.length !== actualGeneric.typeArguments.length
    ) {
      return err(
        "Type inference mismatch: expected '" +
          patternType +
          "' but got '" +
          actualType +
          "'",
      );
    }

    for (let i = 0; i < patternGeneric.typeArguments.length; i++) {
      const argumentBinding = inferTypeParameterBindings(
        parser,
        patternGeneric.typeArguments[i] ?? "",
        actualGeneric.typeArguments[i] ?? "",
        bindings,
      );
      if (!argumentBinding.ok) {
        return argumentBinding;
      }
    }

    return ok(undefined);
  }

  return err(
    "Type inference mismatch: expected '" +
      patternType +
      "' but got '" +
      actualType +
      "'",
  );
}

export function instantiateFunctionInfo(
  parser: Parser,
  functionName: string,
  explicitTypeArguments: string[] | undefined,
  args: ASTNode[],
): Result<FunctionInfo, string> {
  const functionInfo = parser.functions.get(functionName);
  if (!functionInfo) {
    return err("Function '" + functionName + "' is not defined");
  }

  if (functionInfo.typeParameters.length === 0) {
    if (explicitTypeArguments && explicitTypeArguments.length > 0) {
      return err(
        "Function '" +
          functionName +
          "' is not generic and cannot take type arguments",
      );
    }
    return ok(functionInfo);
  }

  if (
    explicitTypeArguments &&
    explicitTypeArguments.length !== functionInfo.typeParameters.length
  ) {
    return err(
      "Function '" +
        functionName +
        "' expects " +
        functionInfo.typeParameters.length +
        " type arguments, got " +
        explicitTypeArguments.length,
    );
  }

  const substitutions = new Map<string, string>();
  if (explicitTypeArguments) {
    const explicitSubstitutions = createTypeParameterSubstitutions(
      functionInfo.typeParameters,
      explicitTypeArguments,
      functionName,
      "Function",
    );
    if (!explicitSubstitutions.ok) {
      return explicitSubstitutions;
    }

    for (const [typeParameter, typeArgument] of explicitSubstitutions.value) {
      substitutions.set(typeParameter, typeArgument);
    }
  }

  if (args.length !== functionInfo.parameters.length) {
    return err(
      "Callable '" +
        functionName +
        "' expects " +
        functionInfo.parameters.length +
        " arguments, got " +
        args.length,
    );
  }

  const savedGenericTypeParameters = [...parser.genericTypeParameters];
  parser.genericTypeParameters = [
    ...savedGenericTypeParameters,
    ...functionInfo.typeParameters,
  ];

  for (let i = 0; i < functionInfo.parameters.length; i++) {
    const parameter = functionInfo.parameters[i];
    const argNode = args[i];
    if (!parameter || !argNode) {
      continue;
    }

    const actualType = inferExpressionType(argNode, parser);
    if (!actualType.ok) {
      parser.genericTypeParameters = savedGenericTypeParameters;
      return actualType;
    }

    const bindingResult = inferTypeParameterBindings(
      parser,
      parameter.type,
      actualType.value,
      substitutions,
    );
    if (!bindingResult.ok) {
      parser.genericTypeParameters = savedGenericTypeParameters;
      if (explicitTypeArguments) {
        return bindingResult;
      }
    }
  }

  parser.genericTypeParameters = savedGenericTypeParameters;

  for (const typeParameter of functionInfo.typeParameters) {
    if (!substitutions.has(typeParameter)) {
      return err(
        "Cannot infer type argument for generic parameter '" +
          typeParameter +
          "' in function '" +
          functionName +
          "'",
      );
    }
  }

  const specializedParameters: FunctionParameter[] = [];
  for (const parameter of functionInfo.parameters) {
    const specializedType = substituteTypeParameters(
      parser,
      parameter.type,
      substitutions,
    );
    if (!specializedType.ok) {
      return specializedType;
    }

    specializedParameters.push({
      ...parameter,
      type: specializedType.value,
    });
  }

  const specializedReturnType = substituteTypeParameters(
    parser,
    functionInfo.returnType,
    substitutions,
  );
  if (!specializedReturnType.ok) {
    return specializedReturnType;
  }

  return ok({
    typeParameters: [],
    parameters: specializedParameters,
    returnType: specializedReturnType.value,
  });
}

export function getStructInfoForType(
  parser: Parser,
  typeStr: string,
): Result<StructInfo, string> {
  const cachedInfo = parser.structs.get(typeStr);
  if (cachedInfo && cachedInfo.typeParameters.length === 0) {
    return ok(cachedInfo);
  }

  const genericType = parseGenericTypeString(typeStr);
  if (!genericType) {
    if (cachedInfo) {
      return ok(cachedInfo);
    }

    return err("Struct '" + typeStr + "' is not defined");
  }

  const baseInfo = parser.structs.get(genericType.baseType);
  if (!baseInfo) {
    return err("Struct '" + genericType.baseType + "' is not defined");
  }

  const substitutions = createTypeParameterSubstitutions(
    baseInfo.typeParameters,
    genericType.typeArguments,
    genericType.baseType,
    "Struct",
  );
  if (!substitutions.ok) {
    return substitutions;
  }

  const specializedFields: StructField[] = [];
  for (const field of baseInfo.fields) {
    const specializedType = substituteTypeParameters(
      parser,
      field.type,
      substitutions.value,
    );
    if (!specializedType.ok) {
      return specializedType;
    }

    specializedFields.push({
      ...field,
      type: specializedType.value,
    });
  }

  const specializedStructInfo: StructInfo = {
    typeParameters: [],
    fields: specializedFields,
  };
  parser.structs.set(typeStr, specializedStructInfo);
  return ok(specializedStructInfo);
}

export function isKnownNamedType(parser: Parser, typeStr: string): boolean {
  if (isGenericTypeParameter(parser, typeStr)) {
    return true;
  }

  const genericType = parseGenericTypeString(typeStr);
  if (genericType) {
    if (!parser.structNames.has(genericType.baseType)) {
      return false;
    }

    const structInfo = parser.structs.get(genericType.baseType);
    if (
      structInfo &&
      structInfo.typeParameters.length !== genericType.typeArguments.length
    ) {
      return false;
    }

    return genericType.typeArguments.every(
      (typeArgument) => validateTypeWithStructs(parser, typeArgument).ok,
    );
  }

  const directStructInfo = parser.structs.get(typeStr);
  return (
    VALID_TYPES.has(typeStr) ||
    (directStructInfo && directStructInfo.typeParameters.length === 0) ||
    (!directStructInfo && parser.structNames.has(typeStr)) ||
    parser.aliasDeclarations.has(typeStr)
  );
}

export function isUnionType(typeStr: string): boolean {
  return parseUnionTypeString(typeStr) !== undefined;
}

export function getUnionTypeArms(typeStr: string): string[] {
  return parseUnionTypeString(typeStr) ?? [typeStr];
}

export function joinUnionTypeArms(arms: string[]): string {
  return arms.join(" | ");
}

export function formatFunctionType(
  parameterTypes: string[],
  returnType: string,
): string {
  return "(" + parameterTypes.join(", ") + ") => " + returnType;
}

export function inferReturnTypesFromNode(
  parser: Parser,
  node: ASTNode,
): Result<string[], string> {
  if (node.kind === "return") {
    const returnType = inferExpressionType(node.value, parser);
    return returnType.ok ? ok([returnType.value]) : returnType;
  }

  if (node.kind === "block") {
    const collectedTypes: string[] = [];
    for (const statement of node.statements) {
      const statementTypes = inferReturnTypesFromNode(parser, statement);
      if (!statementTypes.ok) {
        return statementTypes;
      }
      collectedTypes.push(...statementTypes.value);
    }
    return ok(collectedTypes);
  }

  if (node.kind === "if") {
    const thenTypes = inferReturnTypesFromNode(parser, node.thenBranch);
    if (!thenTypes.ok) {
      return thenTypes;
    }

    const elseTypes: Result<string[], string> = node.elseBranch
      ? inferReturnTypesFromNode(parser, node.elseBranch)
      : ok([]);
    if (!elseTypes.ok) {
      return elseTypes;
    }

    return ok([...thenTypes.value, ...elseTypes.value]);
  }

  if (node.kind === "while") {
    return inferReturnTypesFromNode(parser, node.body);
  }

  return ok([]);
}

export function inferFunctionReturnTypeFromBody(
  parser: Parser,
  body: ASTNode,
): Result<string, string> {
  if (
    body.kind === "destructure" ||
    body.kind === "assign" ||
    body.kind === "field-assign" ||
    body.kind === "array-assign" ||
    body.kind === "deref-assign"
  ) {
    return ok("Void");
  }

  const explicitReturnTypes = inferReturnTypesFromNode(parser, body);
  if (!explicitReturnTypes.ok) {
    return explicitReturnTypes;
  }

  if (body.kind === "block") {
    const hasImplicitResult = !(
      body.result.kind === "number" && body.result.value === "0"
    );

    if (hasImplicitResult) {
      return inferExpressionType(body.result, parser);
    }

    if (explicitReturnTypes.value.length === 0) {
      return ok("Void");
    }
  }

  if (explicitReturnTypes.value.length > 0) {
    let returnType = explicitReturnTypes.value[0] ?? "Void";
    for (let i = 1; i < explicitReturnTypes.value.length; i++) {
      const nextType = explicitReturnTypes.value[i];
      if (!nextType) {
        continue;
      }
      returnType = combineBranchTypes(returnType, nextType);
    }
    return ok(returnType);
  }

  return inferExpressionType(body, parser);
}

export function inferContainerMemberType(
  parser: Parser,
  object: ASTNode,
  fieldName: string,
): Result<string, string> {
  const objectType = inferExpressionType(object, parser);
  if (!objectType.ok) {
    return objectType;
  }

  const objectInfo = parser.objects.get(objectType.value);
  if (objectInfo) {
    const binding = objectInfo.scope.members.get(fieldName);
    if (!binding) {
      return err(
        "Object '" + objectInfo.name + "' has no member '" + fieldName + "'",
      );
    }

    return ok(binding.type);
  }

  const structInfo = parser.structs.get(objectType.value);
  if (!structInfo && !parseGenericTypeString(objectType.value)) {
    return err(
      "Cannot access field on non-struct type '" + objectType.value + "'",
    );
  }

  const resolvedStructInfo = getStructInfoForType(parser, objectType.value);
  if (!resolvedStructInfo.ok) {
    return resolvedStructInfo;
  }

  const field = resolvedStructInfo.value.fields.find(
    (candidate) => candidate.name === fieldName,
  );
  if (!field) {
    return err(
      "Struct '" + objectType.value + "' has no field '" + fieldName + "'",
    );
  }

  return ok(field.type);
}

export function getCallableInfo(
  parser: Parser,
  callee: ASTNode,
): Result<ParsedFunctionType, string> {
  if (callee.kind === "variable") {
    const fnInfo = parser.functions.get(callee.name);
    if (fnInfo) {
      return ok({
        parameterTypes: fnInfo.parameters.map((parameter) => parameter.type),
        returnType: fnInfo.returnType,
      });
    }

    const variableInfo = getVariable(parser, callee.name);
    if (!variableInfo.ok) {
      return err("Function or closure '" + callee.name + "' is not defined");
    }

    const parsedFunctionType = parseFunctionTypeString(variableInfo.value.type);
    return parsedFunctionType
      ? ok(parsedFunctionType)
      : err("Variable '" + callee.name + "' is not callable");
  }

  const resolvedThisMember = resolveThisMemberAccess(callee);
  if (!resolvedThisMember.ok) {
    return resolvedThisMember;
  }
  if (resolvedThisMember.value) {
    const parsedFunctionType = parseFunctionTypeString(
      resolvedThisMember.value.binding.type,
    );
    return parsedFunctionType
      ? ok(parsedFunctionType)
      : err(
          "Member '" +
            resolvedThisMember.value.memberName +
            "' is not callable",
        );
  }

  const calleeType = inferExpressionType(callee, parser);
  if (!calleeType.ok) {
    return calleeType;
  }

  const parsedFunctionType = parseFunctionTypeString(calleeType.value);
  return parsedFunctionType
    ? ok(parsedFunctionType)
    : err("Expression is not callable");
}

export function validateCallArguments(
  parser: Parser,
  callableDescription: string,
  args: ASTNode[],
  parameterTypes: string[],
): Result<ASTNode[], string> {
  if (args.length !== parameterTypes.length) {
    return err(
      "Callable '" +
        callableDescription +
        "' expects " +
        parameterTypes.length +
        " arguments, got " +
        args.length,
    );
  }

  const coercedArgs: ASTNode[] = [];
  for (let i = 0; i < args.length; i++) {
    const argNode = args[i];
    const expectedType = parameterTypes[i];
    if (!argNode || !expectedType) {
      continue;
    }

    const coercedArg = coerceExpressionToType(parser, argNode, expectedType);
    if (!coercedArg.ok) {
      return err(
        "Argument " +
          (i + 1) +
          " for '" +
          callableDescription +
          "' is invalid: " +
          coercedArg.error,
      );
    }

    coercedArgs.push(coercedArg.value);
  }

  return ok(coercedArgs);
}

export function validateArgumentNodes(
  args: ASTNode[],
  // eslint-disable-next-line no-unused-vars
  validator: (arg: ASTNode) => Result<undefined, string>,
): Result<undefined, string> {
  for (const arg of args) {
    const validation = validator(arg);
    if (!validation.ok) {
      return validation;
    }
  }

  return ok(undefined);
}

export function arePointerTypesCompatible(
  expectedType: string,
  actualType: string,
): boolean {
  if (expectedType === actualType) {
    return true;
  }

  if (actualType.startsWith("*mut ") && expectedType.startsWith("*")) {
    return actualType.slice(5) === expectedType.slice(1);
  }

  return false;
}

export function isTypeAssignable(
  expectedType: string,
  actualType: string,
): boolean {
  if (expectedType === actualType) {
    return true;
  }

  const expectedUnionArms = parseUnionTypeString(expectedType);
  if (expectedUnionArms) {
    return expectedUnionArms.some((arm) => isTypeAssignable(arm, actualType));
  }

  const actualUnionArms = parseUnionTypeString(actualType);
  if (actualUnionArms) {
    return actualUnionArms.every((arm) => isTypeAssignable(expectedType, arm));
  }

  if (expectedType.startsWith("*") || actualType.startsWith("*")) {
    return arePointerTypesCompatible(expectedType, actualType);
  }

  return areTypesCompatible(expectedType, actualType);
}

export function selectMatchingUnionArm(
  unionType: string,
  actualType: string,
): string | undefined {
  const unionArms = parseUnionTypeString(unionType);
  if (!unionArms) {
    return undefined;
  }

  return unionArms.find((arm) => isTypeAssignable(arm, actualType));
}

export function wrapExpressionForUnion(
  expression: ASTNode,
  unionType: string,
  armType: string,
): UnionWrapNode {
  return {
    kind: "union-wrap",
    expression,
    unionType,
    armType,
  };
}

export function appendUnionType(
  parser: Parser,
  leftType: string,
  rightType: string,
  resolveAliases: boolean,
): Result<string, string> {
  if (!resolveAliases) {
    return ok(leftType + " | " + rightType);
  }

  return canonicalizeTypeString(parser, leftType + " | " + rightType);
}

export function resolveAliasName(
  parser: Parser,
  aliasName: string,
  visiting: Set<string>,
): Result<string, string> {
  const cachedType = parser.aliases.get(aliasName);
  if (cachedType) {
    return ok(cachedType);
  }

  if (visiting.has(aliasName)) {
    return err("Cyclic type alias detected involving '" + aliasName + "'");
  }

  const rawTargetType = parser.aliasDeclarations.get(aliasName);
  if (!rawTargetType) {
    return err("Invalid type annotation: " + aliasName);
  }

  visiting.add(aliasName);
  const resolvedType = canonicalizeTypeString(parser, rawTargetType, visiting);
  visiting.delete(aliasName);

  if (!resolvedType.ok) {
    return resolvedType;
  }

  parser.aliases.set(aliasName, resolvedType.value);
  return resolvedType;
}

export function canonicalizeTypeString(
  parser: Parser,
  typeStr: string,
  visiting: Set<string> = new Set<string>(),
): Result<string, string> {
  return rewriteCompositeType(
    parser,
    typeStr,
    (typeName: string): Result<string, string> => {
      if (isGenericTypeParameter(parser, typeName)) {
        return ok(typeName);
      }

      if (VALID_TYPES.has(typeName) || parser.structNames.has(typeName)) {
        const directStructInfo = parser.structs.get(typeName);
        if (directStructInfo && directStructInfo.typeParameters.length > 0) {
          return err(
            "Invalid type annotation: generic struct '" +
              typeName +
              "' requires explicit type arguments",
          );
        }

        return ok(typeName);
      }

      if (parser.aliasDeclarations.has(typeName)) {
        return resolveAliasName(parser, typeName, visiting);
      }

      return err("Invalid type annotation: " + typeName);
    },
    (
      baseType: string,
      mappedTypeArguments: string[],
    ): Result<string, string> => {
      if (!parser.structNames.has(baseType)) {
        return err("Invalid type annotation: " + typeStr);
      }

      const baseInfo = parser.structs.get(baseType);
      if (
        baseInfo &&
        baseInfo.typeParameters.length !== mappedTypeArguments.length
      ) {
        return err(
          "Struct '" +
            baseType +
            "' expects " +
            baseInfo.typeParameters.length +
            " type arguments, got " +
            mappedTypeArguments.length,
        );
      }

      const canonicalGenericType =
        baseType + "<" + mappedTypeArguments.join(", ") + ">";
      if (!baseInfo) {
        return ok(canonicalGenericType);
      }

      const specializedStructInfo = getStructInfoForType(
        parser,
        canonicalGenericType,
      );
      return specializedStructInfo.ok
        ? ok(canonicalGenericType)
        : specializedStructInfo;
    },
  );
}

export function normalizeTypeName(
  parser: Parser,
  typeName: string,
  resolveAliases: boolean,
): Result<string, string> {
  const validateResult = validateTypeWithStructs(parser, typeName);
  if (!validateResult.ok) {
    return validateResult;
  }

  return resolveAliases
    ? canonicalizeTypeString(parser, typeName)
    : ok(typeName);
}

export function inferStructFieldType(
  parser: Parser,
  object: ASTNode,
  fieldName: string,
): Result<string, string> {
  return inferContainerMemberType(parser, object, fieldName);
}

export function evaluateIsType(
  parser: Parser,
  expression: ASTNode,
  checkedType: string,
): Result<boolean, string> {
  const expressionType = inferExpressionType(expression, parser);
  if (!expressionType.ok) {
    return expressionType;
  }

  const unionArms = parseUnionTypeString(expressionType.value);
  if (unionArms) {
    return ok(unionArms.some((arm) => arm === checkedType));
  }

  return ok(expressionType.value === checkedType);
}

export function getTypeNarrowingFromCondition(
  condition: ASTNode,
  parser: Parser,
): TypeNarrowingInfo {
  const trueBranch = new Map<string, string>();
  const falseBranch = new Map<string, string>();

  if (condition.kind !== "is" || condition.expression.kind !== "variable") {
    return { trueBranch, falseBranch };
  }

  const variableName = condition.expression.name;
  const variableInfo = parser.variables.get(variableName);
  if (!variableInfo) {
    return { trueBranch, falseBranch };
  }

  const unionArms = parseUnionTypeString(variableInfo.type);
  if (!unionArms) {
    return { trueBranch, falseBranch };
  }

  if (!unionArms.includes(condition.checkedType)) {
    return { trueBranch, falseBranch };
  }

  trueBranch.set(variableName, condition.checkedType);

  const remainingArms = unionArms.filter(
    (arm) => arm !== condition.checkedType,
  );
  if (remainingArms.length === 1) {
    const remainingArm = remainingArms[0];
    if (remainingArm) {
      falseBranch.set(variableName, remainingArm);
    }
  } else if (remainingArms.length > 1) {
    falseBranch.set(variableName, joinUnionTypeArms(remainingArms));
  }

  return { trueBranch, falseBranch };
}

export function applyVariableTypeNarrowing(
  parser: Parser,
  narrowing: Map<string, string>,
): void {
  for (const [name, narrowedType] of narrowing) {
    const existing = parser.variables.get(name);
    if (!existing) {
      continue;
    }
    parser.variables.set(name, {
      ...existing,
      type: narrowedType,
    });
  }
}

export function expressionHasUnionType(
  parser: Parser,
  expression: ASTNode,
): boolean {
  const expressionType = inferExpressionType(expression, parser);
  return expressionType.ok ? isUnionType(expressionType.value) : false;
}

export function coerceExpressionToType(
  parser: Parser,
  expression: ASTNode,
  expectedType: string,
): Result<ASTNode, string> {
  if (expression.kind === "struct-instantiation") {
    const expectedStructInfo = getStructInfoForType(parser, expectedType);
    if (expectedStructInfo.ok) {
      const expectedGenericType = parseGenericTypeString(expectedType);
      const expressionGenericType = parseGenericTypeString(
        expression.structName,
      );
      const expressionBaseName =
        expressionGenericType?.baseType ?? expression.structName;
      const expectedBaseName = expectedGenericType?.baseType ?? expectedType;

      if (expressionBaseName === expectedBaseName) {
        const coercedFields = expression.fields.map((field) => ({ ...field }));
        for (const field of coercedFields) {
          const declaredField = expectedStructInfo.value.fields.find(
            (candidate) => candidate.name === field.name,
          );
          if (!declaredField) {
            return err(
              "Unknown field '" + field.name + "' in struct instantiation",
            );
          }

          const coercedFieldValue = coerceExpressionToType(
            parser,
            field.value,
            declaredField.type,
          );
          if (!coercedFieldValue.ok) {
            return err(
              "Field '" +
                field.name +
                "' is invalid: " +
                coercedFieldValue.error,
            );
          }
          field.value = coercedFieldValue.value;
        }

        return ok({
          ...expression,
          structName: expectedType,
          fields: coercedFields,
          typeArguments: expectedGenericType?.typeArguments,
        });
      }
    }
  }

  const thisScope = resolveThisScopeNode(expression);
  if (thisScope) {
    const thisValidation = validateThisScopeAgainstStruct(
      parser,
      thisScope,
      expectedType,
    );
    return thisValidation.ok ? ok(expression) : thisValidation;
  }

  const actualTypeResult = inferExpressionType(expression, parser);
  if (!actualTypeResult.ok) {
    return actualTypeResult;
  }

  const actualType = actualTypeResult.value;
  if (!isTypeAssignable(expectedType, actualType)) {
    return err(
      "Type mismatch: expression has type '" +
        actualType +
        "' but variable declared as '" +
        expectedType +
        "'",
    );
  }

  const matchingUnionArm = selectMatchingUnionArm(expectedType, actualType);
  if (matchingUnionArm && !isUnionType(actualType)) {
    return ok(
      wrapExpressionForUnion(expression, expectedType, matchingUnionArm),
    );
  }

  return ok(expression);
}

export function coerceFunctionBodyToReturnType(
  parser: Parser,
  body: ASTNode,
  returnType: string,
): Result<ASTNode, string> {
  if (returnType === "Void") {
    return ok(body);
  }

  if (isUnionType(returnType)) {
    return coerceUnionReturnValue(parser, body, returnType);
  }

  if (body.kind === "block") {
    const coercedResult = coerceExpressionToType(
      parser,
      body.result,
      returnType,
    );
    if (!coercedResult.ok) {
      return coercedResult;
    }

    return ok({
      ...body,
      result: coercedResult.value,
    });
  }

  return coerceExpressionToType(parser, body, returnType);
}

export function coerceUnionReturnValue(
  parser: Parser,
  node: ASTNode,
  returnType: string,
): Result<ASTNode, string> {
  if (node.kind === "block") {
    const coercedResult = coerceUnionReturnValue(
      parser,
      node.result,
      returnType,
    );
    if (!coercedResult.ok) {
      return coercedResult;
    }

    return ok({
      ...node,
      result: coercedResult.value,
    });
  }

  if (node.kind === "if" && node.elseBranch !== undefined) {
    const thenBranch = coerceUnionReturnValue(
      parser,
      node.thenBranch,
      returnType,
    );
    if (!thenBranch.ok) {
      return thenBranch;
    }

    const elseBranch = coerceUnionReturnValue(
      parser,
      node.elseBranch,
      returnType,
    );
    if (!elseBranch.ok) {
      return elseBranch;
    }

    return ok({
      ...node,
      thenBranch: thenBranch.value,
      elseBranch: elseBranch.value,
    });
  }

  return coerceExpressionToType(parser, node, returnType);
}

export function combineBranchTypes(
  leftType: string,
  rightType: string,
): string {
  if (isTypeAssignable(leftType, rightType)) {
    return leftType;
  }

  if (isTypeAssignable(rightType, leftType)) {
    return rightType;
  }

  const combinedArms = [
    ...getUnionTypeArms(leftType),
    ...getUnionTypeArms(rightType),
  ];
  const uniqueArms = combinedArms.filter(
    (arm, index) => combinedArms.indexOf(arm) === index,
  );
  return joinUnionTypeArms(uniqueArms);
}

export function ensureExpressionType(
  parser: Parser,
  expr: ASTNode,
  expectedType: string,
): Result<undefined, string> {
  const exprTypeResult = inferExpressionType(expr, parser);
  if (!exprTypeResult.ok) {
    return exprTypeResult;
  }
  if (exprTypeResult.value !== expectedType) {
    return err(
      "Type mismatch: expression has type '" +
        exprTypeResult.value +
        "' but variable declared as '" +
        expectedType +
        "'",
    );
  }
  return ok(undefined);
}

export function inferReferenceType(
  parser: Parser,
  operand: ASTNode,
  operator: "&" | "&mut",
): Result<string, string> {
  const prefix = operator === "&mut" ? "*mut " : "*";

  if (operand.kind === "array-slice") {
    const operandTypeResult = inferExpressionType(operand, parser);
    if (!operandTypeResult.ok) {
      return operandTypeResult;
    }
    return ok(prefix + operandTypeResult.value);
  }

  if (operand.kind !== "variable") {
    return err("Cannot take address of non-variable expression");
  }

  const arrayInfo = getArrayLikeInfo(operand, parser);
  if (arrayInfo && !arrayInfo.isSlice) {
    return ok(prefix + "[" + arrayInfo.elementType + "]");
  }

  const operandTypeResult = inferExpressionType(operand, parser);
  if (!operandTypeResult.ok) {
    return operandTypeResult;
  }
  return ok(prefix + operandTypeResult.value);
}

export function getBracketedTypeInner(typeStr: string): string | undefined {
  if (!typeStr.startsWith("[") || !typeStr.endsWith("]")) {
    return undefined;
  }
  return typeStr.slice(1, -1);
}

export function getBracketedTypeParts(typeStr: string): string[] | undefined {
  const inner = getBracketedTypeInner(typeStr);
  return inner === undefined ? undefined : splitTopLevel(inner, ";");
}

export function applyPointerDecorators(
  baseType: string,
  pointerDepth: number,
  isMutable: boolean,
): string {
  let typeStr = baseType;
  for (let i = 0; i < pointerDepth; i++) {
    if (i === pointerDepth - 1 && isMutable) {
      typeStr = "*mut " + typeStr;
    } else {
      typeStr = "*" + typeStr;
    }
  }
  return typeStr;
}

export function getTypeFromLiteral(numericLiteral: string): string | undefined {
  let pos = 0;

  if (pos < numericLiteral.length && numericLiteral[pos] === "-") {
    pos++;
  }

  while (pos < numericLiteral.length && isDigit(numericLiteral[pos])) {
    pos++;
  }

  if (pos < numericLiteral.length && numericLiteral[pos] === ".") {
    pos++;

    while (pos < numericLiteral.length && isDigit(numericLiteral[pos])) {
      pos++;
    }
  }

  return pos < numericLiteral.length
    ? numericLiteral.substring(pos)
    : undefined;
}

export function validateNegativeType(
  literal: string,
): Result<undefined, string> {
  if (!literal.startsWith("-")) {
    return ok(undefined);
  }

  const type = getTypeFromLiteral(literal);
  if (type && !type.startsWith("I") && !type.startsWith("F")) {
    return err("Cannot apply negative sign to unsigned type: " + literal);
  }

  return ok(undefined);
}

// Infer the type of an expression
export function inferExpressionType(
  expr: ASTNode,
  parser: Parser,
): Result<string, string> {
  if (expr.kind === "union-wrap") {
    return ok(expr.unionType);
  }

  if (expr.kind === "array-slice") {
    const arrayInfo = getArrayLikeInfo(expr.array, parser);
    if (!arrayInfo) {
      return err("Cannot infer element type of array slice");
    }
    return ok("[" + arrayInfo.elementType + "]");
  }

  if (expr.kind === "number") {
    const numValue = expr.value;
    let typeStr = "";
    for (let i = numValue.length - 1; i >= 0; i--) {
      if (isLetter(numValue[i]) || numValue[i] === "_") {
        typeStr = numValue[i] + typeStr;
      } else {
        break;
      }
    }
    return ok(typeStr || "I32");
  }

  if (expr.kind === "boolean") {
    return ok("Bool");
  }

  if (expr.kind === "char") {
    return ok("Char");
  }

  if (expr.kind === "string") {
    return ok("*[Char]");
  }

  if (expr.kind === "module-reference") {
    return ok(expr.type);
  }

  if (expr.kind === "variable") {
    const varResult = getVariable(parser, expr.name);
    if (!varResult.ok) {
      return varResult;
    }
    return ok(varResult.value.type);
  }

  if (expr.kind === "move") {
    return ok(expr.type);
  }

  if (expr.kind === "this") {
    return err("Cannot infer type of expression");
  }

  if (expr.kind === "struct-instantiation") {
    if (expr.typeArguments && expr.typeArguments.length > 0) {
      return ok(expr.structName);
    }

    const resolvedStructInfo = parser.structs.get(expr.structName);
    if (resolvedStructInfo && resolvedStructInfo.typeParameters.length === 0) {
      return ok(expr.structName);
    }

    return err("Cannot infer type of generic struct instantiation");
  }

  if (expr.kind === "array-literal") {
    if (expr.generator && expr.repeatCount !== undefined) {
      const generatorType = inferZeroArgCallableReturnType(
        expr.generator,
        parser,
      );
      if (!generatorType.ok) {
        return generatorType;
      }
      return ok("[" + generatorType.value + ";" + expr.repeatCount + "]");
    }

    if (expr.elemType) {
      return ok("[" + expr.elemType + ";" + expr.elements.length + "]");
    }

    if (expr.elements.length > 0) {
      const firstType = inferExpressionType(
        expr.elements[0] as ASTNode,
        parser,
      );
      if (!firstType.ok) {
        return firstType;
      }
      return ok("[" + firstType.value + ";" + expr.elements.length + "]");
    }

    return err("Cannot infer type of empty array literal");
  }

  if (expr.kind === "field-access") {
    const resolvedThisMember = resolveThisMemberAccess(expr);
    if (!resolvedThisMember.ok) {
      return resolvedThisMember;
    }
    if (resolvedThisMember.value) {
      return ok(resolvedThisMember.value.binding.type);
    }

    if (expr.fieldName === "length" && getArrayLikeInfo(expr.object, parser)) {
      return ok("USize");
    }
    return inferStructFieldType(parser, expr.object, expr.fieldName);
  }

  if (expr.kind === "is") {
    return ok("Bool");
  }

  if (expr.kind === "match") {
    if (expr.cases.length === 0) {
      return err("Cannot infer type of expression");
    }

    let resultType: string | undefined;
    for (const matchCase of expr.cases) {
      const caseType = inferExpressionType(matchCase.result, parser);
      if (!caseType.ok) {
        return caseType;
      }
      resultType =
        resultType === undefined
          ? caseType.value
          : combineBranchTypes(resultType, caseType.value);
    }

    return resultType ? ok(resultType) : err("Cannot infer type of expression");
  }

  if (expr.kind === "unary-op") {
    if (expr.operator === "&" || expr.operator === "&mut") {
      return inferReferenceType(parser, expr.operand, expr.operator);
    }

    if (expr.operator === "*") {
      const operandTypeResult = inferExpressionType(expr.operand, parser);
      if (!operandTypeResult.ok) {
        return operandTypeResult;
      }
      const ptrType = operandTypeResult.value;
      if (!ptrType.startsWith("*")) {
        return err("Cannot dereference non-pointer type: " + ptrType);
      }
      return ok(
        ptrType.startsWith("*mut ") ? ptrType.slice(5) : ptrType.slice(1),
      );
    }
  }

  if (
    expr.kind === "binary" ||
    expr.kind === "comparison" ||
    expr.kind === "logical"
  ) {
    if (expr.kind === "comparison" || expr.kind === "logical") {
      return ok("Bool");
    }

    const leftTypeResult = inferExpressionType(expr.left, parser);
    if (!leftTypeResult.ok) {
      return leftTypeResult;
    }
    const rightTypeResult = inferExpressionType(expr.right, parser);
    if (!rightTypeResult.ok) {
      return rightTypeResult;
    }

    if (
      leftTypeResult.value.startsWith("*") ||
      rightTypeResult.value.startsWith("*")
    ) {
      return err("Pointer arithmetic not supported");
    }

    return leftTypeResult;
  }

  if (expr.kind === "unary-logical") {
    return ok("Bool");
  }

  if (expr.kind === "read") {
    return ok(expr.type);
  }

  if (expr.kind === "closure") {
    const paramTypes = expr.parameters.map((param) => param.type).join(", ");
    return ok("(" + paramTypes + ") => " + expr.returnType);
  }

  if (expr.kind === "function-call") {
    if (expr.returnType) {
      return ok(expr.returnType);
    }

    const fnInfo = parser.functions.get(expr.name);
    if (fnInfo) {
      return ok(fnInfo.returnType);
    }

    const varResult = getVariable(parser, expr.name);
    if (varResult.ok) {
      const parsedFunctionType = parseFunctionTypeString(varResult.value.type);
      if (parsedFunctionType) {
        return ok(parsedFunctionType.returnType);
      }
    }

    return err("Cannot infer return type of callable '" + expr.name + "'");
  }

  if (expr.kind === "call") {
    const callableInfo = getCallableInfo(parser, expr.callee);
    return callableInfo.ok ? ok(callableInfo.value.returnType) : callableInfo;
  }

  if (expr.kind === "array-access") {
    const arrayInfo = getArrayLikeInfo(expr.array, parser);
    if (arrayInfo) {
      return ok(arrayInfo.elementType);
    }
    return err("Cannot infer element type of array access");
  }

  if (expr.kind === "block") {
    return inferExpressionType(expr.result, parser);
  }

  if (expr.kind === "if") {
    const savedVariables = new Map(parser.variables);
    const narrowing = getTypeNarrowingFromCondition(expr.condition, parser);

    applyVariableTypeNarrowing(parser, narrowing.trueBranch);
    const thenType = inferExpressionType(expr.thenBranch, parser);
    parser.variables = new Map(savedVariables);
    if (!thenType.ok) {
      return thenType;
    }

    if (!expr.elseBranch) {
      return thenType;
    }

    applyVariableTypeNarrowing(parser, narrowing.falseBranch);
    const elseType = inferExpressionType(expr.elseBranch, parser);
    parser.variables = savedVariables;
    if (!elseType.ok) {
      return elseType;
    }

    return ok(combineBranchTypes(thenType.value, elseType.value));
  }

  return err("Cannot infer type of expression");
}

export function getVariable(
  parser: Parser,
  name: string,
): Result<VariableInfo, string> {
  const varInfo = parser.variables.get(name);
  if (!varInfo) {
    const scopeBinding = findScopeBinding(parser.currentScope, name);
    if (!scopeBinding) {
      return err("Variable '" + name + "' is not defined");
    }

    return ok({
      type: scopeBinding.type,
      mutable: scopeBinding.mutable,
      moved: false,
    });
  }
  if (varInfo.moved) {
    return err("Variable '" + name + "' was moved and cannot be used");
  }
  return ok(varInfo);
}

// Validate if a number satisfies refinement constraints
export function validateConstraints(
  value: string,
  refinement: RefinementType,
  variables?: Map<string, VariableInfo>,
  parser?: Parser,
): boolean {
  // Parse the numeric value
  const numValue = Number(value);
  if (isNaN(numValue)) {
    return false; // Can't validate non-numeric values
  }

  // Build groups of constraints separated by OR
  // Constraints with isOr=true are OR'd with the previous group
  let currentAndGroup: RefinementConstraint[] = [];
  let constraintGroups: RefinementConstraint[][] = [];

  for (const constraint of refinement.constraints) {
    if (constraint.isOr) {
      // Start new OR group
      if (currentAndGroup.length > 0) {
        constraintGroups.push(currentAndGroup);
        currentAndGroup = [];
      }
    }
    currentAndGroup.push(constraint);
  }
  if (currentAndGroup.length > 0) {
    constraintGroups.push(currentAndGroup);
  }

  // If no groups were created (all AND), validate all constraints
  if (constraintGroups.length === 0) {
    for (const constraint of refinement.constraints) {
      if (!validateSingleConstraint(numValue, constraint, variables, parser)) {
        return false;
      }
    }
    return true;
  }

  // If we have groups (OR), at least one group must be fully satisfied
  for (const group of constraintGroups) {
    let groupSatisfied = true;
    for (const constraint of group) {
      if (!validateSingleConstraint(numValue, constraint, variables, parser)) {
        groupSatisfied = false;
        break;
      }
    }
    if (groupSatisfied) {
      return true; // At least one OR group is satisfied
    }
  }

  return false;
}

// Try to evaluate an expression to a number at compile-time given variable context
export function tryEvaluateExpression(
  expr: ASTNode,
  variables: Map<string, VariableInfo>,
  parser: Parser,
): EvaluationResult {
  // Base case: numeric literal
  if (expr.kind === "number") {
    const num = Number(expr.value);
    return isNaN(num) ? { success: false } : { success: true, value: num };
  }

  // Variable reference - look it up and try to use its known value
  if (expr.kind === "variable") {
    const varInfo = variables.get(expr.name);
    if (!varInfo || !varInfo.initValue) {
      // Can't evaluate if variable not found or value not tracked
      return { success: false };
    }
    // Evaluate the stored initialization value
    const num = Number(varInfo.initValue);
    return isNaN(num) ? { success: false } : { success: true, value: num };
  }

  // Binary operations (arithmetic)
  if (expr.kind === "binary") {
    const leftEval = tryEvaluateExpression(expr.left, variables, parser);
    const rightEval = tryEvaluateExpression(expr.right, variables, parser);

    if (
      !leftEval.success ||
      !rightEval.success ||
      leftEval.value === undefined ||
      rightEval.value === undefined
    ) {
      return { success: false };
    }

    const left = leftEval.value as number;
    const right = rightEval.value as number;
    let result = 0;

    switch (expr.operator) {
      case "+":
        result = left + right;
        break;
      case "-":
        result = left - right;
        break;
      case "*":
        result = left * right;
        break;
      case "/":
        if (right === 0) return { success: false };
        result = left / right;
        break;
      case "%":
        if (right === 0) return { success: false };
        result = left % right;
        break;
      default:
        return { success: false };
    }

    return { success: true, value: result };
  }

  // Other expressions can't be evaluated at compile-time
  return { success: false };
}

export function validateSingleConstraint(
  numValue: number,
  constraint: RefinementConstraint,
  variables?: Map<string, VariableInfo>,
  parser?: Parser,
): boolean {
  // Try to evaluate the constraint value
  let constraintVal: number;

  if (constraint.valueExpr && variables && parser) {
    // Evaluate expression
    const evalResult = tryEvaluateExpression(
      constraint.valueExpr,
      variables,
      parser,
    );
    if (!evalResult.success || evalResult.value === undefined) {
      // Can't evaluate - fail the constraint
      return false;
    }
    constraintVal = evalResult.value as number;
  } else {
    // Fall back to string representation
    constraintVal = Number(constraint.value);
    if (isNaN(constraintVal)) {
      return false;
    }
  }

  let satisfied = false;
  switch (constraint.operator) {
    case ">":
      satisfied = numValue > constraintVal;
      break;
    case "<":
      satisfied = numValue < constraintVal;
      break;
    case ">=":
      satisfied = numValue >= constraintVal;
      break;
    case "<=":
      satisfied = numValue <= constraintVal;
      break;
    case "==":
      satisfied = numValue === constraintVal;
      break;
    case "!=":
      satisfied = numValue !== constraintVal;
      break;
  }
  return satisfied;
}

// Extract refinement constraints from a comparison expression (for type narrowing)
// e.g., "x > 100" yields { baseType: "I32", constraints: [{ operator: ">", value: "100" }] }
export function extractConstraintsFromComparison(
  condition: ASTNode,
  parser: Parser,
): Map<string, RefinementType> {
  const constraints = new Map<string, RefinementType>();

  if (condition.kind === "comparison") {
    const comp = condition as ComparisonNode;

    // Simple case: variable OP value, e.g., x > 100
    if (
      comp.left.kind === "variable" &&
      (comp.right.kind === "number" || comp.right.kind === "variable")
    ) {
      const varName = comp.left.name;
      const varInfo = parser.variables.get(varName);

      if (varInfo) {
        const rightValue =
          comp.right.kind === "number"
            ? (comp.right as NumberNode).value
            : (comp.right as VariableNode).name;

        const refinement: RefinementType = {
          baseType: varInfo.type,
          constraints: [
            {
              operator: comp.operator,
              value: rightValue,
              baseType: varInfo.type,
            },
          ],
        };
        constraints.set(varName, refinement);
      }
    }
    // Reverse case: value OP variable, e.g., 100 < x
    else if (
      comp.right.kind === "variable" &&
      (comp.left.kind === "number" || comp.left.kind === "variable")
    ) {
      const varName = comp.right.name;
      const varInfo = parser.variables.get(varName);

      if (varInfo) {
        const leftValue =
          comp.left.kind === "number"
            ? (comp.left as NumberNode).value
            : (comp.left as VariableNode).name;

        // Flip the operator: 100 < x becomes x > 100
        const flippedOp = flightConstraintOperator(comp.operator);
        const refinement: RefinementType = {
          baseType: varInfo.type,
          constraints: [
            {
              operator: flippedOp,
              value: leftValue,
              baseType: varInfo.type,
            },
          ],
        };
        constraints.set(varName, refinement);
      }
    }
  } else if (condition.kind === "logical") {
    const logic = condition as LogicalNode;

    if (logic.operator === "&&") {
      // Combine constraints from both sides
      const leftConstraints = extractConstraintsFromComparison(
        logic.left,
        parser,
      );
      const rightConstraints = extractConstraintsFromComparison(
        logic.right,
        parser,
      );

      // Merge constraints for the same variable
      for (const [varName, refinement] of leftConstraints) {
        constraints.set(varName, refinement);
      }
      for (const [varName, refinement] of rightConstraints) {
        const existing = constraints.get(varName);
        if (existing && existing.baseType === refinement.baseType) {
          // Combine AND constraints
          existing.constraints.push(...refinement.constraints);
        } else {
          constraints.set(varName, refinement);
        }
      }
    }
    // TODO: Handle OR constraints for type narrowing (more complex)
  }

  return constraints;
}

// Flip comparison operator for constraint extraction (e.g., < becomes >)
export function flightConstraintOperator(
  op: "<" | ">" | "<=" | ">=" | "==" | "!=",
): "<" | ">" | "<=" | ">=" | "==" | "!=" {
  switch (op) {
    case "<":
      return ">";
    case ">":
      return "<";
    case "<=":
      return ">=";
    case ">=":
      return "<=";
    default:
      return op; // == and != remain the same
  }
}

// Check if a variable can be assigned to a refined type given current proven constraints
export function canAssignToRefinedType(
  varName: string,
  requiredRefinement: RefinementType,
  parser: Parser,
): boolean {
  // Check if we have proof for this variable
  const varInfo = parser.variables.get(varName);

  // If the variable has a known initialization value (literal), use that to prove the constraint
  if (varInfo && varInfo.initValue) {
    return validateConstraints(
      varInfo.initValue,
      requiredRefinement,
      parser.variables,
      parser,
    );
  }

  // Check if we have proven constraints for this variable
  const proven = parser.provenConstraints.get(varName);

  if (!proven) {
    // No proven constraints - can't assign
    return false;
  }

  // Check if proven constraints satisfy the required refinement
  if (proven.baseType !== requiredRefinement.baseType) {
    return false; // Type mismatch
  }

  // For each required constraint, check if it's proven
  // This is a simplified check: proven constraints must exactly match required ones
  // (or be stricter, but that's complex to determine for expression-based constraints)
  for (const reqConstraint of requiredRefinement.constraints) {
    let found = false;
    for (const provenConstraint of proven.constraints) {
      // Try to match constraints by evaluating them
      // First try simple string match
      if (
        provenConstraint.operator === reqConstraint.operator &&
        provenConstraint.value === reqConstraint.value
      ) {
        found = true;
        break;
      }

      // If mismatch try evaluating proven constraint to see if it's equivalent
      if (provenConstraint.operator === reqConstraint.operator) {
        // Both are same operator, evaluate the values
        let provenVal: number | undefined;
        let reqVal: number | undefined;

        if (provenConstraint.valueExpr) {
          const evalResult = tryEvaluateExpression(
            provenConstraint.valueExpr,
            parser.variables,
            parser,
          );
          if (evalResult.success && evalResult.value !== undefined) {
            provenVal = evalResult.value as number;
          }
        } else {
          const val = Number(provenConstraint.value);
          if (!isNaN(val)) provenVal = val;
        }

        if (reqConstraint.valueExpr) {
          const evalResult = tryEvaluateExpression(
            reqConstraint.valueExpr,
            parser.variables,
            parser,
          );
          if (evalResult.success && evalResult.value !== undefined) {
            reqVal = evalResult.value as number;
          }
        } else {
          const val = Number(reqConstraint.value);
          if (!isNaN(val)) reqVal = val;
        }

        if (
          provenVal !== undefined &&
          reqVal !== undefined &&
          provenVal === reqVal
        ) {
          found = true;
          break;
        }
      }
    }
    if (!found) {
      return false; // Required constraint not proven
    }
  }

  return true;
}
