// Generated by scripts/refactor/split-compile.ts

import { err, ok } from "../../types";
import type { Result } from "../../types";
import type {
  ASTNode,
  FunctionNode,
  LetNode,
  ObjectInfo,
  Parser,
  StructInfo,
  StructInstantiationNode,
} from "../core/ast";
import {
  extendTypeEnvironmentForStatement,
  resolveThisMemberAccess,
} from "../core/scope";
import {
  resolveAliasName,
  validateArgumentNodes,
  validateNegativeType,
} from "./type-system";

/**
 * Helper to validate expressions used in value contexts where they must produce a value
 * (e.g., initializers, returns, if branches)
 */
export function validateExpressionAsValue(
  node: ASTNode,
): Result<undefined, string> {
  // If expressions without else cannot be used in value contexts
  if (node.kind === "if" && node.elseBranch === undefined) {
    return err(
      "If expression without else clause cannot be used in value context",
    );
  }

  return validateAST(node);
}

export function validateStatementList(
  statements: ASTNode[],
): Result<undefined, string> {
  for (const statement of statements) {
    const validation = validateAST(statement);
    if (!validation.ok) {
      return validation;
    }
  }

  return ok(undefined);
}

export function validateAST(node: ASTNode): Result<undefined, string> {
  if (node.kind === "number") {
    return validateNegativeType(node.value);
  }

  if (node.kind === "boolean") {
    return ok(undefined);
  }

  if (node.kind === "char") {
    return ok(undefined);
  }

  if (node.kind === "string") {
    return ok(undefined);
  }

  if (node.kind === "is") {
    return validateAST(node.expression);
  }

  if (node.kind === "union-wrap") {
    return validateAST(node.expression);
  }

  if (
    node.kind === "read" ||
    node.kind === "module-reference" ||
    node.kind === "variable" ||
    node.kind === "move" ||
    node.kind === "this"
  ) {
    return ok(undefined);
  }

  if (node.kind === "let") {
    // Validate initializer expression - must produce a value
    return validateExpressionAsValue(node.initializer);
  }

  if (
    node.kind === "extern-module" ||
    node.kind === "extern-function" ||
    node.kind === "extern-let" ||
    node.kind === "extern-type"
  ) {
    return ok(undefined);
  }

  if (node.kind === "destructure") {
    return validateStatementList(node.statements);
  }

  if (node.kind === "assign") {
    return validateAST(node.value);
  }

  if (node.kind === "unary-op") {
    return validateAST(node.operand);
  }

  if (
    node.kind === "binary" ||
    node.kind === "comparison" ||
    node.kind === "logical"
  ) {
    const leftValidation = validateAST(node.left);
    if (!leftValidation.ok) {
      return leftValidation;
    }

    return validateAST(node.right);
  }

  if (node.kind === "unary-logical") {
    return validateAST(node.operand);
  }

  if (node.kind === "block") {
    const statementValidation = validateStatementList(node.statements);
    if (!statementValidation.ok) {
      return statementValidation;
    }
    return validateAST(node.result);
  }

  if (node.kind === "if") {
    // Validate condition
    const condValidation = validateAST(node.condition);
    if (!condValidation.ok) {
      return condValidation;
    }

    // Validate then branch
    const thenValidation = validateAST(node.thenBranch);
    if (!thenValidation.ok) {
      return thenValidation;
    }

    // Validate else branch if present
    if (node.elseBranch !== undefined) {
      const elseValidation = validateAST(node.elseBranch);
      if (!elseValidation.ok) {
        return elseValidation;
      }
    }

    return ok(undefined);
  }

  if (node.kind === "while") {
    // Validate condition
    const condValidation = validateAST(node.condition);
    if (!condValidation.ok) {
      return condValidation;
    }

    // Validate body
    const bodyValidation = validateAST(node.body);
    if (!bodyValidation.ok) {
      return bodyValidation;
    }

    return ok(undefined);
  }

  if (node.kind === "break" || node.kind === "continue") {
    // Validation for break/continue will be done at parser level
    return ok(undefined);
  }

  if (node.kind === "return") {
    // Validate return value - must produce a value
    return validateExpressionAsValue(node.value);
  }

  if (node.kind === "match") {
    // Validate match expression
    const exprValidation = validateAST(node.matchExpr);
    if (!exprValidation.ok) {
      return exprValidation;
    }

    // Validate all case results
    for (const c of node.cases) {
      const caseValidation = validateAST(c.result);
      if (!caseValidation.ok) {
        return caseValidation;
      }
    }

    return ok(undefined);
  }

  if (node.kind === "function") {
    // Validate function body
    return validateAST(node.body);
  }

  if (node.kind === "object") {
    return validateStatementList(node.body);
  }

  if (node.kind === "module") {
    return validateAST(node.body);
  }

  if (node.kind === "type-alias") {
    return ok(undefined);
  }

  if (node.kind === "closure") {
    return validateAST(node.body);
  }

  if (node.kind === "function-call") {
    return validateArgumentNodes(node.arguments, validateAST);
  }

  if (node.kind === "call") {
    const calleeValidation = validateAST(node.callee);
    if (!calleeValidation.ok) {
      return calleeValidation;
    }

    return validateArgumentNodes(node.arguments, validateAST);
  }

  if (node.kind === "struct") {
    // Structs are just declarations, no body validation needed
    return ok(undefined);
  }

  if (node.kind === "array-literal") {
    if (node.generator) {
      return validateAST(node.generator);
    }

    for (const element of node.elements) {
      const elementValidation = validateAST(element);
      if (!elementValidation.ok) {
        return elementValidation;
      }
    }
    return ok(undefined);
  }

  if (node.kind === "array-access") {
    const arrayValidation = validateAST(node.array);
    if (!arrayValidation.ok) {
      return arrayValidation;
    }
    return validateAST(node.index);
  }

  if (node.kind === "array-slice") {
    return validateAST(node.array);
  }

  if (node.kind === "array-assign") {
    const arrayValidation = validateAST(node.array);
    if (!arrayValidation.ok) {
      return arrayValidation;
    }
    const indexValidation = validateAST(node.index);
    if (!indexValidation.ok) {
      return indexValidation;
    }
    return validateAST(node.value);
  }

  if (node.kind === "struct-instantiation") {
    // Validate all field values
    for (const field of node.fields) {
      const fieldValidation = validateAST(field.value);
      if (!fieldValidation.ok) {
        return fieldValidation;
      }
    }
    return ok(undefined);
  }

  if (node.kind === "field-access") {
    // Validate the object being accessed
    return validateAST(node.object);
  }

  if (node.kind === "field-assign") {
    // Validate the object being assigned to and the value
    const objectValidation = validateAST(node.object);
    if (!objectValidation.ok) {
      return objectValidation;
    }
    return validateAST(node.value);
  }

  return ok(undefined);
}

export function resolveTypeAliases(parser: Parser): Result<void, string> {
  for (const aliasName of parser.aliasDeclarations.keys()) {
    const resolvedAlias = resolveAliasName(
      parser,
      aliasName,
      new Set<string>(),
    );
    if (!resolvedAlias.ok) {
      return resolvedAlias;
    }
  }

  return ok(undefined);
}

/**
 * Returns the struct name for the given node if it's a struct-instantiation,
 * or looks up the variable type for a variable node.
 */
export function getNodeContainerType(
  node: ASTNode,
  structs: Map<string, StructInfo>,
  objects: Map<string, ObjectInfo>,
  typeEnv: Map<string, string>,
): string | undefined {
  if (node.kind === "module-reference") {
    return node.type;
  }

  if (node.kind === "struct-instantiation") {
    return (node as StructInstantiationNode).structName;
  }
  if (node.kind === "object") {
    return node.type;
  }
  if (node.kind === "variable") {
    return typeEnv.get(node.name);
  }
  if (node.kind === "field-access") {
    const parentType = getNodeContainerType(
      node.object,
      structs,
      objects,
      typeEnv,
    );
    if (!parentType) return undefined;

    if (objects.has(parentType)) {
      const binding = objects
        .get(parentType)
        ?.scope.members.get(node.fieldName);
      return binding?.type;
    }

    const structInfo = structs.get(parentType);
    const field = structInfo?.fields.find((f) => f.name === node.fieldName);
    return field?.type;
  }
  return undefined;
}

/**
 * Validates struct field access, mutability, and type compatibility.
 * 'typeEnv' maps variable names to their declared types.
 */
export function validateStructSemantics(
  node: ASTNode,
  structs: Map<string, StructInfo>,
  objects: Map<string, ObjectInfo>,
  typeEnv: Map<string, string>,
): Result<undefined, string> {
  if (node.kind === "destructure") {
    let env = typeEnv;
    for (const statement of node.statements) {
      const validation = validateStructSemantics(
        statement,
        structs,
        objects,
        env,
      );
      if (!validation.ok) {
        return validation;
      }
      env = extendTypeEnvironmentForStatement(env, statement);
    }
    return ok(undefined);
  }

  if (node.kind === "let") {
    const letNode = node as LetNode;
    // Check struct vs primitive type mismatch
    if (
      letNode.initializer.kind === "struct-instantiation" &&
      !structs.has(letNode.type)
    ) {
      return err(
        "Type mismatch: cannot assign struct to variable of type '" +
          letNode.type +
          "'",
      );
    }
    if (
      structs.has(letNode.type) &&
      letNode.initializer.kind !== "struct-instantiation" &&
      letNode.initializer.kind !== "variable" &&
      letNode.initializer.kind !== "field-access"
    ) {
      // Only error if initializer is clearly not a struct (e.g. a number literal)
      if (
        letNode.initializer.kind === "number" ||
        letNode.initializer.kind === "boolean"
      ) {
        return err(
          "Type mismatch: variable '" +
            letNode.name +
            "' expects struct type '" +
            letNode.type +
            "'",
        );
      }
    }
    // Register variable type in environment for sub-expressions
    typeEnv = new Map(typeEnv);
    typeEnv.set(letNode.name, letNode.type);
    return validateStructSemantics(
      letNode.initializer,
      structs,
      objects,
      typeEnv,
    );
  }

  if (node.kind === "extern-let") {
    typeEnv = new Map(typeEnv);
    typeEnv.set(node.name, node.type);
    return ok(undefined);
  }

  if (
    node.kind === "extern-module" ||
    node.kind === "extern-function" ||
    node.kind === "extern-type"
  ) {
    return ok(undefined);
  }

  if (node.kind === "object") {
    let env = new Map(typeEnv);
    env.set(node.name, node.type);
    for (const statement of node.body) {
      const validation = validateStructSemantics(
        statement,
        structs,
        objects,
        env,
      );
      if (!validation.ok) {
        return validation;
      }
      if (statement.kind === "let") {
        env.set(statement.name, statement.type);
      } else if (statement.kind === "object") {
        env.set(statement.name, statement.type);
      }
    }
    return ok(undefined);
  }

  if (node.kind === "field-access" || node.kind === "field-assign") {
    const resolvedThisMember = resolveThisMemberAccess(node);
    if (!resolvedThisMember.ok) {
      return resolvedThisMember;
    }
    if (resolvedThisMember.value) {
      return node.kind === "field-access"
        ? ok(undefined)
        : validateStructSemantics(node.value, structs, objects, typeEnv);
    }

    const objResult = validateStructSemantics(
      node.object,
      structs,
      objects,
      typeEnv,
    );
    if (!objResult.ok) return objResult;

    const containerType = getNodeContainerType(
      node.object,
      structs,
      objects,
      typeEnv,
    );
    const structInfo = containerType ? structs.get(containerType) : undefined;
    const objectInfo = containerType ? objects.get(containerType) : undefined;

    if (node.kind === "field-access") {
      if (objectInfo) {
        if (!objectInfo.scope.members.has(node.fieldName)) {
          return err(
            "Object '" +
              objectInfo.name +
              "' has no member '" +
              node.fieldName +
              "'",
          );
        }
        return ok(undefined);
      }

      if (
        structInfo &&
        !structInfo.fields.find((f) => f.name === node.fieldName)
      ) {
        return err(
          "Struct '" +
            containerType +
            "' has no field '" +
            node.fieldName +
            "'",
        );
      }
      return ok(undefined);
    }

    // field-assign
    if (objectInfo) {
      const binding = objectInfo.scope.members.get(node.fieldName);
      if (!binding) {
        return err(
          "Object '" +
            objectInfo.name +
            "' has no member '" +
            node.fieldName +
            "'",
        );
      }
      if (!binding.assignable) {
        return err("Member '" + node.fieldName + "' is read-only");
      }
      return validateStructSemantics(node.value, structs, objects, typeEnv);
    }

    if (structInfo) {
      const field = structInfo.fields.find((f) => f.name === node.fieldName);
      if (field && !field.mutable) {
        return err(
          "Field '" +
            node.fieldName +
            "' of struct '" +
            containerType +
            "' is read-only",
        );
      }
    }
    return validateStructSemantics(node.value, structs, objects, typeEnv);
  }

  // For block nodes, thread the typeEnv through sequentially
  if (node.kind === "block") {
    let env = typeEnv;
    for (const stmt of node.statements) {
      const r = validateStructSemantics(stmt, structs, objects, env);
      if (!r.ok) return r;

      env = extendTypeEnvironmentForStatement(env, stmt);
    }
    return validateStructSemantics(node.result, structs, objects, env);
  }

  // Recurse into child nodes generically
  if (
    node.kind === "binary" ||
    node.kind === "comparison" ||
    node.kind === "logical"
  ) {
    const l = validateStructSemantics(node.left, structs, objects, typeEnv);
    if (!l.ok) return l;
    return validateStructSemantics(node.right, structs, objects, typeEnv);
  }

  if (node.kind === "unary-logical") {
    return validateStructSemantics(node.operand, structs, objects, typeEnv);
  }

  if (node.kind === "if") {
    const c = validateStructSemantics(
      node.condition,
      structs,
      objects,
      typeEnv,
    );
    if (!c.ok) return c;
    const t = validateStructSemantics(
      node.thenBranch,
      structs,
      objects,
      typeEnv,
    );
    if (!t.ok) return t;
    if (node.elseBranch) {
      return validateStructSemantics(
        node.elseBranch,
        structs,
        objects,
        typeEnv,
      );
    }
    return ok(undefined);
  }

  if (node.kind === "while") {
    const c = validateStructSemantics(
      node.condition,
      structs,
      objects,
      typeEnv,
    );
    if (!c.ok) return c;
    return validateStructSemantics(node.body, structs, objects, typeEnv);
  }

  if (node.kind === "function") {
    // Build parameter type env for function body
    const fnEnv = new Map(typeEnv);
    for (const p of (node as FunctionNode).parameters) {
      fnEnv.set(p.name, p.type);
    }
    return validateStructSemantics(node.body, structs, objects, fnEnv);
  }

  if (node.kind === "closure") {
    const closureEnv = new Map(typeEnv);
    for (const p of node.parameters) {
      closureEnv.set(p.name, p.type);
    }
    return validateStructSemantics(node.body, structs, objects, closureEnv);
  }

  if (node.kind === "function-call") {
    return validateArgumentNodes(node.arguments, (arg: ASTNode) =>
      validateStructSemantics(arg, structs, objects, typeEnv),
    );
  }

  if (node.kind === "call") {
    const calleeValidation = validateStructSemantics(
      node.callee,
      structs,
      objects,
      typeEnv,
    );
    if (!calleeValidation.ok) return calleeValidation;
    return validateArgumentNodes(node.arguments, (arg: ASTNode) =>
      validateStructSemantics(arg, structs, objects, typeEnv),
    );
  }

  if (node.kind === "type-alias") {
    return ok(undefined);
  }

  if (node.kind === "array-literal") {
    if (node.generator) {
      return validateStructSemantics(node.generator, structs, objects, typeEnv);
    }

    for (const element of node.elements) {
      const r = validateStructSemantics(element, structs, objects, typeEnv);
      if (!r.ok) return r;
    }
    return ok(undefined);
  }

  if (node.kind === "array-access") {
    const arrayResult = validateStructSemantics(
      node.array,
      structs,
      objects,
      typeEnv,
    );
    if (!arrayResult.ok) return arrayResult;
    return validateStructSemantics(node.index, structs, objects, typeEnv);
  }

  if (node.kind === "array-slice") {
    return validateStructSemantics(node.array, structs, objects, typeEnv);
  }

  if (node.kind === "array-assign") {
    const arrayResult = validateStructSemantics(
      node.array,
      structs,
      objects,
      typeEnv,
    );
    if (!arrayResult.ok) return arrayResult;
    const indexResult = validateStructSemantics(
      node.index,
      structs,
      objects,
      typeEnv,
    );
    if (!indexResult.ok) return indexResult;
    return validateStructSemantics(node.value, structs, objects, typeEnv);
  }

  if (node.kind === "unary-op") {
    return validateStructSemantics(node.operand, structs, objects, typeEnv);
  }

  if (node.kind === "union-wrap") {
    return validateStructSemantics(node.expression, structs, objects, typeEnv);
  }

  if (node.kind === "this" || node.kind === "move") {
    return ok(undefined);
  }

  if (node.kind === "struct-instantiation") {
    for (const f of (node as StructInstantiationNode).fields) {
      const r = validateStructSemantics(f.value, structs, objects, typeEnv);
      if (!r.ok) return r;
    }
    return ok(undefined);
  }

  if (node.kind === "return") {
    return validateStructSemantics(node.value, structs, objects, typeEnv);
  }

  if (node.kind === "assign") {
    return validateStructSemantics(node.value, structs, objects, typeEnv);
  }

  return ok(undefined);
}
