// Generated by scripts/refactor/split-compile.ts

import type {
  ASTNode,
  BlockNode,
  ExternBindingInfo,
  FunctionParameter,
  MatchCase,
  ScopeFrame,
} from "../../../commonMain/compiler/core/ast";
import { createModuleResultName } from "../../../commonMain/compiler/core/project";
import { isDigit } from "../../../commonMain/compiler/core/tokenization";

interface CleanupBinding {
  name: string;
  destructorFunction: string;
}

interface CodegenBindingInfo {
  destructorFunction?: string;
}

interface CodegenContext {
  variables: Map<string, CodegenBindingInfo>;
}

interface GeneratedStatementCode {
  code: string;
  context: CodegenContext;
  cleanupBindings: CleanupBinding[];
}

export function createCodegenContext(): CodegenContext {
  return { variables: new Map() };
}

export function cloneCodegenContext(context: CodegenContext): CodegenContext {
  return { variables: new Map(context.variables) };
}

export function createFunctionCodegenContext(
  parameters: FunctionParameter[],
): CodegenContext {
  const context = createCodegenContext();
  for (const parameter of parameters) {
    context.variables.set(parameter.name, {
      destructorFunction: parameter.destructorFunction,
    });
  }
  return context;
}

export function getCleanupBindings(statement: ASTNode): CleanupBinding[] {
  if (statement.kind === "let" && statement.destructorFunction) {
    return [
      {
        name: statement.name,
        destructorFunction: statement.destructorFunction,
      },
    ];
  }

  if (statement.kind === "destructure") {
    return statement.statements.flatMap((nestedStatement) =>
      getCleanupBindings(nestedStatement),
    );
  }

  return [];
}

export function extendCodegenContextForStatement(
  context: CodegenContext,
  statement: ASTNode,
): CodegenContext {
  const nextContext = cloneCodegenContext(context);

  if (statement.kind === "let") {
    nextContext.variables.set(statement.name, {
      destructorFunction: statement.destructorFunction,
    });
    return nextContext;
  }

  if (statement.kind === "destructure") {
    for (const nestedStatement of statement.statements) {
      nextContext.variables.set(nestedStatement.name, {
        destructorFunction: nestedStatement.destructorFunction,
      });
    }
  }

  return nextContext;
}

export function codegenCleanup(binding: CleanupBinding): string {
  const emittedName = codegenVariableName(binding.name);
  return (
    "if (" +
    emittedName +
    " !== undefined) { " +
    binding.destructorFunction +
    "(" +
    emittedName +
    "); " +
    emittedName +
    " = undefined; }"
  );
}

export function codegenCleanupBindings(bindings: CleanupBinding[]): string {
  return [...bindings]
    .reverse()
    .map((binding) => codegenCleanup(binding))
    .join(" ");
}

export function hasMeaningfulBlockResult(block: BlockNode): boolean {
  return !(block.result.kind === "number" && block.result.value === "0");
}

export function generateStatementCodeWithContext(
  statements: ASTNode[],
  context: CodegenContext,
): GeneratedStatementCode {
  let currentContext = cloneCodegenContext(context);
  const cleanupBindings: CleanupBinding[] = [];
  const code = statements
    .map((stmt) => {
      const statementCode = codegenAST(stmt, currentContext);
      cleanupBindings.push(...getCleanupBindings(stmt));
      currentContext = extendCodegenContextForStatement(currentContext, stmt);
      return statementCode.endsWith(";") ? statementCode : statementCode + ";";
    })
    .join(" ");

  return {
    code,
    context: currentContext,
    cleanupBindings,
  };
}

export function codegenBlockFragment(
  block: BlockNode,
  context: CodegenContext,
  mode: "statement" | "value" | "effect",
  initialCleanupBindings: CleanupBinding[] = [],
): string {
  const statementResult = generateStatementCodeWithContext(
    block.statements,
    context,
  );
  const cleanupCode = codegenCleanupBindings([
    ...initialCleanupBindings,
    ...statementResult.cleanupBindings,
  ]);

  if (mode === "statement") {
    if (cleanupCode.length === 0) {
      return statementResult.code;
    }

    return (
      "try { " + statementResult.code + " } finally { " + cleanupCode + " }"
    );
  }

  const resultCode = codegenAST(block.result, statementResult.context);
  const bodyCode =
    mode === "value"
      ? statementResult.code + " return " + resultCode + ";"
      : statementResult.code +
        (hasMeaningfulBlockResult(block) ? resultCode + ";" : "");

  if (cleanupCode.length === 0) {
    return bodyCode;
  }

  return "try { " + bodyCode + " } finally { " + cleanupCode + " }";
}

export function codegenProgramReturn(node: ASTNode): string {
  const context = createCodegenContext();
  if (node.kind === "block") {
    return codegenBlockFragment(node, context, "value") + ";";
  }

  return "return " + codegenAST(node, context) + ";";
}

export function codegenProgramEvaluation(
  node: ASTNode,
  resultName: string,
): string {
  if (node.kind === "block") {
    const statementResult = generateStatementCodeWithContext(
      node.statements,
      createCodegenContext(),
    );
    return (
      statementResult.code +
      " " +
      resultName +
      " = " +
      codegenAST(node.result, statementResult.context) +
      ";"
    );
  }

  return resultName + " = " + codegenAST(node, createCodegenContext()) + ";";
}

export function codegenExternalProviderHelpers(): string {
  return (
    "function __tuffExternValue(_tuffProvider, _tuffModuleName, _tuffExportName) { " +
    "if (!_tuffProvider || !(_tuffExportName in _tuffProvider)) { " +
    'throw new Error(`External module "${_tuffModuleName}" is missing export "${_tuffExportName}"`); ' +
    "} return _tuffProvider[_tuffExportName]; } " +
    "function __tuffExternFunction(_tuffProvider, _tuffModuleName, _tuffExportName) { " +
    "const _tuffValue = __tuffExternValue(_tuffProvider, _tuffModuleName, _tuffExportName); " +
    'if (typeof _tuffValue !== "function") { ' +
    'throw new Error(`External module "${_tuffModuleName}" export "${_tuffExportName}" is not callable`); ' +
    "} return _tuffValue; }"
  );
}

export function codegenExternalProviderLoad(
  runtimeName: string,
  source: string,
): string {
  return (
    "const " +
    runtimeName +
    " = (() => { const module = { exports: {} }; const exports = module.exports; " +
    source +
    "; return module.exports; })();"
  );
}

export function codegenExternBindings(
  moduleName: string,
  providerVar: string,
  externBindings: ExternBindingInfo[],
): string {
  return externBindings
    .map((binding) => {
      const accessor =
        binding.kind === "function"
          ? "__tuffExternFunction"
          : "__tuffExternValue";
      return (
        "const " +
        binding.name +
        " = " +
        accessor +
        "(" +
        providerVar +
        ", " +
        JSON.stringify(moduleName) +
        ", " +
        JSON.stringify(binding.name) +
        ");"
      );
    })
    .join(" ");
}

export function codegenFunctionLikeDeclaration(
  name: string | undefined,
  parameters: FunctionParameter[],
  returnType: string,
  body: ASTNode,
  isDestructor: boolean = false,
): string {
  const paramList = parameters
    .map((parameter) => codegenVariableName(String(parameter.name)))
    .join(", ");
  const bodyCode = codegenFunctionLikeBody(
    body,
    returnType,
    parameters,
    isDestructor,
  );
  const functionName = name ? " " + name : "";
  const suffix = name ? ";" : "";
  return (
    "function" +
    functionName +
    "(" +
    paramList +
    ") { " +
    bodyCode +
    " }" +
    suffix
  );
}

export function codegenFunctionLikeBody(
  body: ASTNode,
  returnType: string,
  parameters: FunctionParameter[],
  isDestructor: boolean,
): string {
  const context = createFunctionCodegenContext(parameters);
  const parameterCleanupBindings = (isDestructor ? [] : parameters)
    .filter((parameter) => parameter.destructorFunction)
    .map((parameter) => ({
      name: parameter.name,
      destructorFunction: parameter.destructorFunction ?? "",
    }));

  let bodyCode = "";

  if (body.kind === "block") {
    return codegenBlockFragment(
      body,
      context,
      returnType === "Void" ? "effect" : "value",
      parameterCleanupBindings,
    );
  }

  const cleanupCode = codegenCleanupBindings(parameterCleanupBindings);
  if (returnType === "Void") {
    bodyCode = codegenAST(body, context);
    return cleanupCode.length === 0
      ? bodyCode
      : "try { " + bodyCode + "; } finally { " + cleanupCode + " }";
  }

  bodyCode = "return " + codegenAST(body, context) + ";";
  return cleanupCode.length === 0
    ? bodyCode
    : "try { " + bodyCode + " } finally { " + cleanupCode + " }";
}

export function extractNumberValue(numericLiteral: string): string {
  let pos = 0;
  let result = "";

  // Handle optional sign
  if (pos < numericLiteral.length && numericLiteral[pos] === "-") {
    result += "-";
    pos++;
  }

  // Extract digits
  while (pos < numericLiteral.length && isDigit(numericLiteral[pos])) {
    result += numericLiteral[pos];
    pos++;
  }

  // Extract optional decimal part
  if (pos < numericLiteral.length && numericLiteral[pos] === ".") {
    result += ".";
    pos++;

    while (pos < numericLiteral.length && isDigit(numericLiteral[pos])) {
      result += numericLiteral[pos];
      pos++;
    }
  }

  return result || "0";
}

export function codegenVariableName(name: string): string {
  return name === "this" ? "_tuffThisParam" : name;
}

export function generateStatementCode(
  statements: ASTNode[],
  context: CodegenContext = createCodegenContext(),
): string {
  return generateStatementCodeWithContext(statements, context).code;
}

export function codegenThisScopeObject(scope: ScopeFrame): string {
  const parentExpression = scope.parent
    ? codegenThisScopeObject(scope.parent)
    : undefined;

  const memberDefinitions: string[] = [];
  const emittedMembers = new Set<string>();
  for (const [name, binding] of scope.members) {
    emittedMembers.add(name);
    if (binding.kind === "function") {
      memberDefinitions.push(
        "get " +
          name +
          "() { return (..._tuffArgs) => " +
          name +
          ".length === _tuffArgs.length + 1 ? " +
          name +
          "(_tuffThis, ..._tuffArgs) : " +
          name +
          "(..._tuffArgs); }",
      );
      continue;
    }

    memberDefinitions.push("get " + name + "() { return " + name + "; }");
    if (binding.assignable) {
      memberDefinitions.push(
        "set " + name + "(_tuffValue) { " + name + " = _tuffValue; }",
      );
    }
  }

  if (scope.parent?.kind === "object") {
    for (const [name, binding] of scope.parent.members) {
      if (emittedMembers.has(name)) {
        continue;
      }

      if (binding.kind === "function") {
        memberDefinitions.push(
          "get " +
            name +
            "() { return (..._tuffArgs) => _tuffParent." +
            name +
            ".length === _tuffArgs.length + 1 ? _tuffParent." +
            name +
            "(_tuffParent, ..._tuffArgs) : _tuffParent." +
            name +
            "(..._tuffArgs); }",
        );
        continue;
      }

      memberDefinitions.push(
        "get " + name + "() { return _tuffParent." + name + "; }",
      );
      if (binding.assignable) {
        memberDefinitions.push(
          "set " +
            name +
            "(_tuffValue) { _tuffParent." +
            name +
            " = _tuffValue; }",
        );
      }
    }
  }

  memberDefinitions.push(
    scope.parent
      ? "get this() { return _tuffParent; }"
      : "get this() { return _tuffThis; }",
  );

  const parentInit = scope.parent
    ? " const _tuffParent = " + parentExpression + ";"
    : "";

  return (
    "(() => {" +
    parentInit +
    " const _tuffThis = { " +
    memberDefinitions.join(", ") +
    " }; return _tuffThis; })()"
  );
}

export function codegenAST(
  node: ASTNode,
  context: CodegenContext = createCodegenContext(),
): string {
  if (node.kind === "number") {
    // Extract numeric part, stripping type annotation
    return extractNumberValue(node.value);
  }

  if (node.kind === "string") {
    return "[" + node.value.join(", ") + "]";
  }

  if (node.kind === "char") {
    return node.value;
  }

  if (node.kind === "boolean") {
    // Convert boolean to number (1 for true, 0 for false)
    return node.value ? "1" : "0";
  }

  if (node.kind === "is") {
    if (node.runtimeCheck) {
      const expression =
        node.expression.kind === "variable"
          ? codegenVariableName(node.expression.name)
          : codegenAST(node.expression, context);
      return (
        "(() => { const _tuffValue = " +
        expression +
        '; return _tuffValue && _tuffValue.__tuffUnion && _tuffValue.tag === "' +
        node.checkedType +
        '" ? 1 : 0; })()'
      );
    }
    return node.matches ? "1" : "0";
  }

  if (node.kind === "union-wrap") {
    const expression = codegenAST(node.expression, context);
    return (
      '({ __tuffUnion: true, tag: "' +
      node.armType +
      '", value: ' +
      expression +
      " })"
    );
  }

  if (node.kind === "read") {
    return "readValue()";
  }

  if (node.kind === "module-reference") {
    return node.runtimeName;
  }

  if (node.kind === "variable") {
    return (
      "(() => { const _tuffValue = " +
      codegenVariableName(node.name) +
      "; return _tuffValue && _tuffValue.__tuffUnion ? _tuffValue.value : _tuffValue; })()"
    );
  }

  if (node.kind === "move") {
    const emittedName = codegenVariableName(node.name);
    return (
      "(() => { const _tuffMoved = " +
      emittedName +
      "; " +
      emittedName +
      " = undefined; return _tuffMoved; })()"
    );
  }

  if (node.kind === "this") {
    return codegenThisScopeObject(node.scope);
  }

  if (node.kind === "let") {
    const init = codegenAST(node.initializer, context);
    return "var " + codegenVariableName(node.name) + " = " + init;
  }

  if (node.kind === "destructure") {
    return generateStatementCode(node.statements, context);
  }

  if (node.kind === "assign") {
    const value = codegenAST(node.value, context);
    const bindingInfo = context.variables.get(node.name);
    const emittedName = codegenVariableName(node.name);
    if (!bindingInfo?.destructorFunction) {
      return emittedName + " = " + value;
    }

    return (
      "(() => { const _tuffValue = " +
      value +
      "; if (" +
      emittedName +
      " !== undefined) { " +
      bindingInfo.destructorFunction +
      "(" +
      emittedName +
      "); } " +
      emittedName +
      " = _tuffValue; return _tuffValue; })()"
    );
  }

  if (node.kind === "deref-assign") {
    const value = codegenAST(node.value, context);
    // If we know which variable the pointer points to, assign to that variable
    if (node.targetVar) {
      return codegenVariableName(node.targetVar) + " = " + value;
    }
    // Otherwise, fall back to assigning through the pointer
    const target = codegenAST(node.target, context);
    return target + " = " + value;
  }

  if (
    node.kind === "binary" ||
    node.kind === "comparison" ||
    node.kind === "logical"
  ) {
    const left = codegenAST(node.left, context);
    const right = codegenAST(node.right, context);
    // For division with integer types, use Math.trunc for integer division
    if (node.kind === "binary" && node.operator === "/") {
      return "(Math.trunc(" + left + " / " + right + "))";
    }
    return "(" + left + " " + node.operator + " " + right + ")";
  }

  if (node.kind === "unary-logical") {
    const operand = codegenAST(node.operand, context);
    return "(!" + operand + ")";
  }

  if (node.kind === "unary-op") {
    if (node.operator === "*") {
      const operand = codegenAST(node.operand, context);
      // Dereference: *ptr -> ptr (in a simple interpreter, values are already dereferenced)
      return operand;
    } else if (node.operator === "&" || node.operator === "&mut") {
      if (node.operand.kind === "array-slice") {
        return codegenAST(node.operand, context);
      }

      const operand = codegenAST(node.operand, context);
      // Address-of: &x -> x (in our simple model, we just return the variable/value)
      return operand;
    }
  }

  if (node.kind === "block") {
    return codegenBlockFragment(node, context, "value");
  }

  if (node.kind === "if") {
    const condition = codegenAST(node.condition, context);

    let thenCode = "";
    if (node.thenBranch.kind === "block") {
      // Check if block has a meaningful final expression (not just 0)
      const hasResult =
        node.thenBranch.result &&
        !(
          node.thenBranch.result.kind === "number" &&
          node.thenBranch.result.value === "0"
        );

      const stmtCode = codegenBlockFragment(
        node.thenBranch,
        context,
        hasResult && node.elseBranch ? "value" : "statement",
      );
      if (hasResult && node.elseBranch) {
        // Block with meaningful result and there's an else - it's an expression
        thenCode = stmtCode;
      } else {
        // Just statements, no meaningful result
        thenCode = stmtCode;
      }
    } else {
      thenCode = codegenAST(node.thenBranch, context);
    }

    if (node.elseBranch === undefined) {
      // if without else - used as statement
      return "if (" + condition + ") { " + thenCode + " }";
    }

    // if with else - generate else branch code
    let elseCode = "";
    if (node.elseBranch.kind === "block") {
      // Check if block has a meaningful final expression
      const hasResult =
        node.elseBranch.result &&
        !(
          node.elseBranch.result.kind === "number" &&
          node.elseBranch.result.value === "0"
        );

      const stmtCode = codegenBlockFragment(
        node.elseBranch,
        context,
        hasResult ? "value" : "statement",
      );
      if (hasResult) {
        elseCode = stmtCode;
      } else {
        elseCode = stmtCode;
      }
    } else if (node.elseBranch.kind === "if") {
      // else if - the recursive call will generate the correct syntax
      // For nested if nodes, we need to generate them as expressions if blocks are involved
      const innerIfCode = codegenAST(node.elseBranch, context);

      if (node.thenBranch.kind === "block") {
        // Then has statements, use if/else syntax
        return (
          "if (" + condition + ") { " + thenCode + " } else " + innerIfCode
        );
      } else {
        // Both are non-block expressions, so treat as full ternary
        return "(" + condition + " ? " + thenCode + " : " + innerIfCode + ")";
      }
    } else {
      elseCode = codegenAST(node.elseBranch, context);
    }

    // Check if both branches are simple expressions without statements or blocks
    if (node.thenBranch.kind !== "block" && node.elseBranch.kind !== "block") {
      // Both are simple expressions - use ternary
      return "(" + condition + " ? " + thenCode + " : " + elseCode + ")";
    } else {
      // At least one has statements - need to wrap as expression
      // Use IIFE to convert if statement to expression
      return (
        "(function() { if (" +
        condition +
        ") { " +
        thenCode +
        " } else { " +
        elseCode +
        " } }())"
      );
    }
  }

  if (node.kind === "while") {
    const condition = codegenAST(node.condition, context);
    let bodyCode = "";

    if (node.body.kind === "block") {
      bodyCode = codegenBlockFragment(node.body, context, "statement");
    } else {
      bodyCode = codegenAST(node.body, context);
    }

    return "while (" + condition + ") { " + bodyCode + " }";
  }

  if (node.kind === "break") {
    return "break";
  }

  if (node.kind === "continue") {
    return "continue";
  }

  if (node.kind === "return") {
    const value = codegenAST(node.value, context);
    return "return " + value;
  }

  if (node.kind === "match") {
    const matchExpr = codegenAST(node.matchExpr, context);

    // Generate ternary chain for match cases
    // match (x) { case 1 => 10; case 2 => 20; case _ => 0; }
    // becomes: x === 1 ? 10 : x === 2 ? 20 : 0
    let result = "";
    let wildcardCase: MatchCase | undefined;
    const regularCases: MatchCase[] = [];

    for (const c of node.cases) {
      if (c.pattern.type === "wildcard") {
        wildcardCase = c;
      } else {
        regularCases.push(c);
      }
    }

    // Check if all non-wildcard cases are boolean (exhaustive boolean match)
    const isExhaustiveBooleanMatch =
      regularCases.length > 0 &&
      regularCases.every((c) => c.pattern.type === "boolean") &&
      regularCases.length === 2 &&
      regularCases.some((c) => (c.pattern as any).value === true) &&
      regularCases.some((c) => (c.pattern as any).value === false);

    // Build ternary chain for all cases
    if (isExhaustiveBooleanMatch) {
      // Special handling for exhaustive boolean: x === 1 ? trueValue : falseValue
      const trueCase = regularCases.find(
        (c) => (c.pattern as any).value === true,
      );
      const falseCase = regularCases.find(
        (c) => (c.pattern as any).value === false,
      );
      if (trueCase && falseCase) {
        const trueResult = codegenAST(trueCase.result, context);
        const falseResult = codegenAST(falseCase.result, context);
        result = matchExpr + " === 1 ? " + trueResult + " : " + falseResult;
      }
    } else {
      // Regular ternary chain
      regularCases.forEach((c, i) => {
        const caseResult = codegenAST(c.result, context);

        if (c.pattern.type === "literal") {
          result += matchExpr + " === " + c.pattern.value + " ? " + caseResult;
        } else if (c.pattern.type === "boolean") {
          result +=
            matchExpr + " === " + c.pattern.value
              ? "1"
              : "0" + " ? " + caseResult;
        }

        if (i < regularCases.length - 1 || wildcardCase) {
          result += " : ";
        }
      });

      // Add wildcard case at the end
      if (wildcardCase) {
        const wildcardResult = codegenAST(wildcardCase.result, context);
        result += wildcardResult;
      }
    }

    return "(" + result + ")";
  }

  if (node.kind === "function") {
    return codegenFunctionLikeDeclaration(
      node.name,
      node.parameters,
      node.returnType,
      node.body,
      node.isDestructor,
    );
  }

  if (node.kind === "object") {
    const statements = generateStatementCode(node.body, context);
    const runtimeObject = codegenThisScopeObject(node.scope);
    return (
      "const " +
      node.name +
      " = (() => { " +
      statements +
      " return " +
      runtimeObject +
      "; })()"
    );
  }

  if (node.kind === "module") {
    const runtimeObject = codegenThisScopeObject(node.scope);
    const resultName = createModuleResultName(node.runtimeName);
    const externPrelude =
      node.externalProviderVar &&
      node.externBindings &&
      node.externBindings.length > 0
        ? codegenExternBindings(
            node.moduleName,
            node.externalProviderVar,
            node.externBindings,
          ) + " "
        : "";
    return (
      "let " +
      resultName +
      "; const " +
      node.runtimeName +
      " = (() => { " +
      externPrelude +
      codegenProgramEvaluation(node.body, resultName) +
      " return " +
      runtimeObject +
      "; })()"
    );
  }

  if (node.kind === "type-alias") {
    return "0";
  }

  if (node.kind === "contract") {
    return "0";
  }

  if (
    node.kind === "extern-module" ||
    node.kind === "extern-function" ||
    node.kind === "extern-let" ||
    node.kind === "extern-type"
  ) {
    return "0";
  }

  if (node.kind === "closure") {
    return codegenFunctionLikeDeclaration(
      undefined,
      node.parameters,
      node.returnType,
      node.body,
      false,
    );
  }

  if (node.kind === "function-call") {
    // Generate function call
    const argList = node.arguments
      .map((arg) => codegenAST(arg, context))
      .join(", ");

    return node.name + "(" + argList + ")";
  }

  if (node.kind === "call") {
    const callee = codegenAST(node.callee, context);
    const argList = node.arguments
      .map((arg) => codegenAST(arg, context))
      .join(", ");
    return callee + "(" + argList + ")";
  }

  if (node.kind === "struct") {
    // Struct declarations don't generate code themselves
    // They are just type definitions
    return "0";
  }

  if (node.kind === "struct-instantiation") {
    // Generate struct instantiation as JavaScript object
    const fields = node.fields
      .map((f) => {
        const value = codegenAST(f.value, context);
        return f.name + ": " + value;
      })
      .join(", ");

    return "{ " + fields + " }";
  }

  if (node.kind === "array-literal") {
    if (node.generator && node.repeatCount !== undefined) {
      const generator = codegenAST(node.generator, context);
      return (
        "(() => { const _tuffArray = []; const _tuffGenerator = (" +
        generator +
        "); for (let _tuffIndex = 0; _tuffIndex < " +
        node.repeatCount +
        "; _tuffIndex += 1) { _tuffArray.push(_tuffGenerator()); } return _tuffArray; })()"
      );
    }

    // Generate array literal as a JavaScript array.
    const elements = node.elements.map((elem) => codegenAST(elem, context));
    return "[" + elements.join(", ") + "]";
  }

  if (node.kind === "array-access") {
    const array = codegenAST(node.array, context);
    const index = codegenAST(node.index, context);
    return (
      "(() => { const _tuffArray = " +
      array +
      "; const _tuffIndex = " +
      index +
      "; return _tuffArray && _tuffArray.__tuffSlice ? _tuffArray.data[_tuffArray.start + _tuffIndex] : _tuffArray[_tuffIndex]; })()"
    );
  }

  if (node.kind === "array-slice") {
    const array = codegenAST(node.array, context);
    return (
      "(() => { const _tuffArray = " +
      array +
      "; const _tuffBase = _tuffArray && _tuffArray.__tuffSlice ? _tuffArray.data : _tuffArray; const _tuffStartOffset = _tuffArray && _tuffArray.__tuffSlice ? _tuffArray.start : 0; const _tuffStart = _tuffStartOffset + " +
      node.start +
      "; const _tuffEnd = _tuffStartOffset + " +
      node.end +
      "; return { __tuffSlice: true, data: _tuffBase, start: _tuffStart, end: _tuffEnd, length: _tuffEnd - _tuffStart }; })()"
    );
  }

  if (node.kind === "array-assign") {
    const array = codegenAST(node.array, context);
    const index = codegenAST(node.index, context);
    const value = codegenAST(node.value, context);
    return (
      "(() => { const _tuffArray = " +
      array +
      "; const _tuffIndex = " +
      index +
      "; const _tuffValue = " +
      value +
      "; if (_tuffArray && _tuffArray.__tuffSlice) { _tuffArray.data[_tuffArray.start + _tuffIndex] = _tuffValue; } else { _tuffArray[_tuffIndex] = _tuffValue; } return _tuffValue; })()"
    );
  }

  if (node.kind === "field-access") {
    // Generate field access
    const obj = codegenAST(node.object, context);
    return obj + "." + node.fieldName;
  }

  if (node.kind === "field-assign") {
    // Generate field assignment
    const obj = codegenAST(node.object, context);
    const value = codegenAST(node.value, context);
    return obj + "." + node.fieldName + " = " + value;
  }

  return "0";
}
