/**
 * Stub compiler from Tuff source to TypeScript output.
 *
 * Tuff language semantics are still TBD, so this currently returns a
 * minimal, valid TypeScript module with metadata comments only.
 */

type IntegerType = "U8" | "U16" | "U32" | "U64" | "I8" | "I16" | "I32" | "I64";

const INTEGER_RANGES: Record<IntegerType, { min: bigint; max: bigint }> = {
  U8: { min: 0n, max: 255n },
  U16: { min: 0n, max: 65535n },
  U32: { min: 0n, max: 4294967295n },
  U64: { min: 0n, max: 18446744073709551615n },
  I8: { min: -128n, max: 127n },
  I16: { min: -32768n, max: 32767n },
  I32: { min: -2147483648n, max: 2147483647n },
  I64: { min: -9223372036854775808n, max: 9223372036854775807n },
};

function compileTypedIntegerLiteral(source: string): string {
  const typedIntegerMatch = /^(\d+)(U8|U16|U32|U64|I8|I16|I32|I64)$/.exec(
    source,
  );
  if (!typedIntegerMatch) {
    throw new Error(`Invalid Tuff literal syntax: ${source}`);
  }

  const numericPart = typedIntegerMatch[1];
  const typeSuffix = typedIntegerMatch[2] as IntegerType;

  const parsed = BigInt(numericPart);
  const { min, max } = INTEGER_RANGES[typeSuffix];
  if (parsed < min || parsed > max) {
    throw new Error(`Tuff literal out of range for ${typeSuffix}: ${source}`);
  }

  if (parsed > BigInt(Number.MAX_SAFE_INTEGER)) {
    throw new Error(
      `Tuff literal cannot be represented safely as JS number in stub mode: ${source}`,
    );
  }

  return [
    "// Generated by compileTuffToTS (stub)",
    "// Typed literal program compiled by stub path.",
    `const __tuff_result: number = ${parsed};`,
    "",
  ].join("\n");
}

export function compileTuffToTS(tuffSource: string): string {
  const source = tuffSource.trim();

  if (source.length === 0) {
    return [
      "// Generated by compileTuffToTS (stub)",
      "// Empty Tuff program currently compiles to numeric zero.",
      "const __tuff_result: number = 0;",
      "",
    ].join("\n");
  }

  if (/^-?[A-Za-z0-9_]+(U8|U16|U32|U64|I8|I16|I32|I64)$/.test(source)) {
    return compileTypedIntegerLiteral(source);
  }

  return [
    "// Generated by compileTuffToTS (stub)",
    "// TODO: Replace with real Tuff -> TypeScript compilation logic.",
    `// Input size: ${tuffSource.length} characters`,
    "export {};",
    "",
  ].join("\n");
}
