/**
 * Stub compiler from Tuff source to TypeScript output.
 *
 * Tuff language semantics are still TBD, so this currently returns a
 * minimal, valid TypeScript module with metadata comments only.
 */
export function compileTuffToTS(tuffSource: string): string {
  return [
    "// Generated by compileTuffToTS (stub)",
    "// TODO: Replace with real Tuff -> TypeScript compilation logic.",
    `// Input size: ${tuffSource.length} characters`,
    "export {};",
    "",
  ].join("\n");
}
