// Generated by scripts/refactor/split-compile.ts

import { err, ok } from "../../types";
import type { Result } from "../../types";
import { formatFunctionType, isTypeAssignable } from "../semantics/type-system";
import type { ASTNode, FunctionParameter, ModuleCompilationInfo, Parser, ResolvedThisMemberAccess, ScopeBinding, ScopeFrame } from "./ast";

export function createScopeFrame(
  parent: ScopeFrame | undefined,
  kind: "normal" | "object" = "normal",
): ScopeFrame {
  return {
    kind,
    members: new Map<string, ScopeBinding>(),
    parent,
  };
}

export function createFunctionScopeBinding(
  parameters: FunctionParameter[],
  returnType: string,
): ScopeBinding {
  return {
    kind: "function",
    type: formatFunctionType(
      parameters.map((parameter) => parameter.type),
      returnType,
    ),
    mutable: false,
    assignable: false,
  };
}

export function registerScopeVariable(
  parser: Parser,
  name: string,
  type: string,
  mutable: boolean,
  assignable: boolean,
): void {
  parser.currentScope.members.set(name, {
    kind: "variable",
    type,
    mutable,
    assignable,
  });
}

export function registerScopeFunction(
  parser: Parser,
  name: string,
  parameters: FunctionParameter[],
  returnType: string,
): void {
  parser.currentScope.members.set(
    name,
    createFunctionScopeBinding(parameters, returnType),
  );
}

export function createObjectTypeName(name: string): string {
  return "__object__" + name;
}

export function registerProjectModulesAsObjects(
  parser: Parser,
  modules: Map<string, ModuleCompilationInfo>,
): void {
  for (const moduleInfo of modules.values()) {
    parser.objects.set(moduleInfo.typeName, {
      name: moduleInfo.moduleName,
      type: moduleInfo.typeName,
      scope: moduleInfo.scope,
    });
  }
}

export function findScopeBinding(
  scope: ScopeFrame | undefined,
  name: string,
): ScopeBinding | undefined {
  let currentScope = scope;

  while (currentScope) {
    const binding = currentScope.members.get(name);
    if (binding) {
      return binding;
    }
    currentScope = currentScope.parent;
  }

  return undefined;
}

export function updateScopeFunctionBinding(
  scope: ScopeFrame,
  name: string,
  parameters: FunctionParameter[],
  returnType: string,
): void {
  scope.members.set(name, createFunctionScopeBinding(parameters, returnType));
}

export function extendTypeEnvironmentForStatement(
  env: Map<string, string>,
  stmt: ASTNode,
): Map<string, string> {
  const nextEnv = new Map(env);

  if (stmt.kind === "let") {
    nextEnv.set(stmt.name, stmt.type);
  } else if (stmt.kind === "object") {
    nextEnv.set(stmt.name, stmt.type);
  } else if (stmt.kind === "destructure") {
    for (const declaration of stmt.statements) {
      if (!declaration.name.startsWith("$tuffDestructure")) {
        nextEnv.set(declaration.name, declaration.type);
      }
    }
  }

  return nextEnv;
}

export function resolveThisScopeNode(node: ASTNode): ScopeFrame | undefined {
  if (node.kind === "this") {
    return node.scope;
  }

  if (node.kind === "field-access" && node.fieldName === "this") {
    const parentScope = resolveThisScopeNode(node.object);
    if (!parentScope) {
      return undefined;
    }
    return parentScope.parent ?? parentScope;
  }

  return undefined;
}

export function resolveThisMemberAccess(
  node: ASTNode,
): Result<ResolvedThisMemberAccess | undefined, string> {
  if (node.kind !== "field-access" || node.fieldName === "this") {
    return ok(undefined);
  }

  const ownerScope = resolveThisScopeNode(node.object);
  if (!ownerScope) {
    return ok(undefined);
  }

  const binding =
    ownerScope.members.get(node.fieldName) ??
    (ownerScope.parent?.kind === "object"
      ? ownerScope.parent.members.get(node.fieldName)
      : undefined);
  if (!binding) {
    return err("Unknown member '" + node.fieldName + "' on this");
  }

  return ok({
    ownerScope,
    memberName: node.fieldName,
    binding,
  });
}

export function validateThisScopeAgainstStruct(
  parser: Parser,
  scope: ScopeFrame,
  expectedType: string,
): Result<undefined, string> {
  const structInfo = parser.structs.get(expectedType);
  if (!structInfo) {
    return err(
      "Type mismatch: expression has type 'this' but variable declared as '" +
        expectedType +
        "'",
    );
  }

  for (const field of structInfo.fields) {
    const binding = scope.members.get(field.name);
    if (!binding) {
      return err(
        "Type mismatch: this is missing required member '" +
          field.name +
          "' for type '" +
          expectedType +
          "'",
      );
    }

    if (!isTypeAssignable(field.type, binding.type)) {
      return err(
        "Type mismatch: this member '" +
          field.name +
          "' has type '" +
          binding.type +
          "' but expected '" +
          field.type +
          "'",
      );
    }
  }

  return ok(undefined);
}